[book]
authors = ["The Bhikkhu Saṅgha"]
language = "en"
multilingual = false
src = "src"
title = "Vinaya Class"

[output.html]
google-analytics = "UA-3557338-14"
additional-css = ["theme/custom.css"]
