# -*- flyspell-lazy-local: nil; mode: Org; eval: (progn (flycheck-mode 0) (flyspell-mode 0) (toggle-truncate-lines 1)) -*-
#+LATEX_CLASS: memoir
#+LATEX_HEADER: \input{./pali-lessons-preamble.tex}
#+LATEX_HEADER: \maxtocdepth{section}
#+LANGUAGE: en_GB
#+OPTIONS: toc:nil tasks:nil H:4 author:nil ':t ^:{} tags:nil
#+TITLE: Pāli Readings
#+AUTHOR: The Bhikkhu Saṅgha

#+begin_export latex
\makeatletter

\newlength{\colOne}\setlength{\colOne}{0.35\linewidth}
\newlength{\colTwo}\setlength{\colTwo}{0.6\linewidth}

\renewenvironment{quote}%
{\list{}{%
    \doubleLineSize
    \listparindent 0pt
    \itemindent    0pt
    \leftmargin    3em
    \rightmargin   3em
    \parsep        0pt
    \topsep        8pt
    \partopsep     0pt}%
\item[] \raggedright}%
{\endlist}

\renewcommand*{\printchaptertitleHook}{%
  \AddToShipoutPictureBG*{%
    \put(\LenToUnit{\paperwidth-25mm-\spinemargin},\LenToUnit{\paperheight-100mm}){%
      \includegraphics[width=25mm]{./images/cases-legend-white-large.png}%
    }%
  }%
}

\renewcommand*\sentenceDiaSolution[2][0.4]{%
  \ifanswerkey%
    \hspace*{-\spinemargin}%
    \begin{minipage}{\paperwidth}%
      \centering%
      \includegraphics[scale=#1]{#2}%
    \end{minipage}%
  \fi%
}

\makeatother

\mainmatter
#+end_export

* Tasks                                                            :noexport:
** Ideas

Slides for the reading? with refs and links

- contact def
- papañca from MN 18
- text with paṭighasamphasso / -sañña
- Jaṭāsutta
- Snp 4.11: Evaṁ sametassa vibhoti rūpaṁ, / Saññānidānā hi papañcasaṅkhā
- feelings growing cool

anki words: collect to sutta decks
Anki check dupl, single apkg

email MhB after

reading yt upload: generate thumbnail with title

Mahābodhi
Feb: video link to Anejo, Kataññuto, Dhirabodhi

* Recording setup with Zoom and OBS                                :noexport:

hide top bar
fullscreen Brave with tldraw, but windowed in qtile
emacs buffer with notes, narrowed, no modeline, white theme

: (hide-mode-line-mode 1)
: (hide-mode-line-mode 0)

Laptop:
- Connect the JABRA mic/speaker, place it on the table
- Record at 60fps with OBS

Record separately on the Mac
- camera feed, in case of showing sth to the camera

OBS: Record only the shared screen (my screen with the tldraw explanation), to
show less of other people's camera feed.

Mac:
- Mac setting: select Jabra speaker from the top bar menu
- Zoom join: enable audio and video
- Start video on Theravada account screen
- Left screen: gallery (people's video) window
- Right screen: highlight window (screen sharing / speaker's video)
- Zoom settings: speaker/microphone: Jabra SPEAK 510 USB
- OBS: Record at 60 FPS

Laptop:
- Mute audio input/output, due to feedback with Mac computer
- Open Zoom in Firefox

ws 3: org notes
ws 4: Brave with tldraw, Simsapa
ws 9: Firefox with Zoom

Use scp to copy recording to laptop.

: cd "~/Videos/Recordings/Pali Readings (Europe)"
: scp "sumedharama@192.168.1.124:/Users/sumedharama/Movies/2025-01-22 13-01-25.mkv" .

** Uploading

Trim lossless with [[https://github.com/mifi/lossless-cut][lossless-cut]]. Fast, no re-encoding.

Upload to YouTube. Playlist is linked from the lessons github page.

https://www.youtube.com/playlist?list=PLxSN2DAE3W85GMLVm8uFV4c9U50q025tx

Title format: ~Bojjhaṅga gilānasutta (2025-01-15)~

Upload settings:

- Visibility: Unlisted
- Playlist: Pāli Readings
- No paid promotion
- No, not Made for Kids
- No, not Altered / generated
- Language: English
- License: Creative Commons
- No embedding
- No notifications
- No remixing
- Category: Education / Lecture
- Comments: Off

* Links                                                            :noexport:

[[https://www.tldraw.com/r/hXdaGU7vKip5vHbAkQa8D?d=v-31.-133.1879.981.uD8B2rmiVHR_6viSS8AOn][tldraw Pāli Readings]]

[[https://www.tldraw.com/r/XXFsr0LAbq5hnpIPk68oZ?d=v-271.-85.1879.981.-MoEVvzvSGwo5y3S6Xo4B][tldraw 2024 (class) edit]]

[[https://www.tldraw.com/ro/PhYEAoE4a35dCVhtF-hEB?d=v-205.-141.1879.1015.page][tldraw 2024 (class) view]]

[[https://www.tldraw.com/r/NBh0Ae8CWE1As8DiFaGI9][tldraw 2024 (solved)]]

* Notes                                                            :noexport:
* 2025-01-29                                                       :noexport:
** AN 5.37 Bhojanasutta

(SC, DPR, [[http://localhost:4848/suttas/an5.37/pli/ms?window_type=Sutta+Study][SSP]])

** Snp 2.10: Uṭṭhānasutta (arrow simile)

http://localhost:4848/suttas/snp2.10/pli/ms?window_type=Sutta+Search

Sermon 10

Uṭṭhahatha nisīdatha,
ko attho supitena vo;
Āturānañhi kā niddā,
sallaviddhāna ruppataṁ.

* 2025-02-13                                                       :noexport:
** MN 1 maññati

seeing earth in the earth
doesn't see earth in earth

#+begin_quote
Idha, bhikkhave, assutavā puthujjano ariyānaṁ adassāvī

ariyadhammassa akovido ariyadhamme avinīto,

sappurisānaṁ adassāvī sappurisadhammassa akovido sappurisadhamme avinīto.

pathaviṁ pathavito sañjānāti;

pathaviṁ pathavito saññatvā pathaviṁ maññati,

pathaviyā maññati, pathavito maññati, pathaviṁ meti maññati,

pathaviṁ abhinandati.

Taṁ kissa hetu? ‘Apariññātaṁ tassā’ti vadāmi.

Āpaṁ ... Tejaṁ ... Vāyaṁ ...

Bhūte ... Deve ... etc.

Diṭṭhaṁ ... Sutaṁ ... Mutaṁ ... Viññātaṁ ...

Nibbānaṁ ...

Yopi so, bhikkhave, bhikkhu sekkho appattamānaso

anuttaraṁ yogakkhemaṁ patthayamāno viharati; sopi:

pathaviṁ pathavito abhijānāti;

pathaviṁ pathavito abhiññāya pathaviṁ mā maññi,

pathaviyā mā maññi, pathavito mā maññi, pathaviṁ meti mā maññi,

pathaviṁ mābhinandi.

Taṁ kissa hetu? ‘Pariññeyyaṁ tassā’ti vadāmi.
#+end_quote

** Definition of Contact

Sermon 4

> *Cakkhuñca paṭicca rūpe ca uppajjati cakkhuviññāṇaṁ, tiṇṇaṁ saṅgati phasso,
> phassapaccayā vedanā, vedanāpaccayā taṇhā, taṇhāpaccayā upādānaṁ,
> upādānapaccayā bhavo, bhavapaccayā jāti, jātipaccayā jarāmaraṇaṁ
> sokaparidevadukkhadomanassūpāyāsā sambhavanti. Evametassa kevalassa
> dukkhakkhandhassa samudayo hoti*.[^fn138]

[^fn138]: S IV 86, *Dukkhasutta*

http://localhost:4848/suttas/sn35.106/pli/ms?window_type=Sutta+Study

* 2025-02-05
** Exercise

#+latex: \renewcommand{\arraystretch}{1.4}

#+ATTR_LATEX: :center nil
| These two ends should not be pursued (/sevati/) by one who has gone forth. |
| \fillin{11cm}{Dveme, bhikkhave, antā pabbajitena na sevitabbā.}            |
| He makes an end of suffering.                                              |
| \fillin{11cm}{So dukkhass'antaṁ karoti.}                                  |
| The man eats edibles (/bhojanīya/) and chewables (/khādanīya/).            |
| \fillin{11cm}{Puriso bhojanīyāni khādanīyāni ca khādati.}                  |
| The rag (/santhata/) is being chewed (/khajjati/) by rats (/undūra/).      |
| \fillin{11cm}{Santhataṁ undūrehi khajjanti.}                              |
| In the past it was cold (/sīta/).                                          |
| \fillin{11cm}{Atīte sītaṁ ahosi.}                                         |
| In the future it will be hot (/uṇha/).                                     |
| \fillin{11cm}{Anāgate uṇhaṁ bhavissati.}                                   |
| The noble disciple considers (/paṭisañcikkhati/) this.                     |
| \fillin{11cm}{Ariyasāvako iti paṭisañcikkhati.}                            |

#+latex: \normalArrayStretch

** MN 9 Sammādiṭṭhisutta, Definition of Name-and-Form                        :anki:
:PROPERTIES:
:DECK_NAME: MN 9 Sammādiṭṭhisutta
:END:

([[https://suttacentral.net/mn9/pli/ms][SC]], [[https://www.digitalpalireader.online/_dprhtml/index.html?loc=m.0.0.0.0.8.0.m&para=30][DPR]], [[http://localhost:4848/suttas/mn9/pli/ms?quote=Katama%25E1%25B9%2581%2520pan%25C4%2581vuso%252C%2520n%25C4%2581mar%25C5%25ABpa%25E1%25B9%2581&window_type=Sutta+Study][SSP]])

#+latex: \vspace*{-0.5\baselineskip}
#+latex: \enlargethispage*{\baselineskip}

#+begin_quote
Āyasmā sāriputto etadavoca: “‘Sammādiṭṭhi sammādiṭṭhī’ti, āvuso, vuccati.

Kittāvatā nu kho, āvuso, ariyasāvako sammādiṭṭhi hoti, ujugatāssa diṭṭhi,

dhamme aveccappasādena samannāgato, āgato imaṁ saddhamman”ti?
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo} H H
| avoca (aor. +acc & +acc)  | said (something to somebody); aor. of vacati            | 10795/dpd | Āyasmā sāriputto etad{{avoca}}: “‘Sammādiṭṭhi sammādiṭṭhī’ti, āvuso, vuccati. |
| vuccati (pr.)             | is said to be; is called; pass. of vacati               | 69965/dpd | Āyasmā sāriputto etadavoca: “‘Sammādiṭṭhi sammādiṭṭhī’ti, āvuso, {{vuccati}}. |
| kittāvatā                 | in what way? [ka + tāva + tā]                           | 21707/dpd | {{Kittāvatā}} nu kho, āvuso, ariyasāvako sammādiṭṭhi hoti                    |
| ujugata (adj.)            | correct; lit. gone straight [uju + gata]                | 14399/dpd | {{ujugat}}āssa diṭṭhi, dhamme aveccappasādena samannāgato                    |
| assa (pron. gen.)         | his; of him; its; of it [ima + ssa] masc.gen.sg. of ima | 9917/dpd  | ujugat{{āssa}} diṭṭhi, dhamme aveccappasādena samannāgato                    |
| diṭṭhi (f.)               | view; belief                                            | 32479/dpd | ujugatāssa {{diṭṭhi}}, dhamme aveccappasādena samannāgato                    |
| aveccappasāda (m.)        | perfect clarity [avecca + pasāda]                       | 10777/dpd | ujugatāssa diṭṭhi, dhamme {{aveccappasādena}} samannāgato                    |
| avecca (ind.)             | perfectly; absolutely; lit. going into                  | 10771/dpd | ujugatāssa diṭṭhi, dhamme {{avecca}}ppasādena samannāgato                    |
| samannāgata (pp. +instr.) | possessing; endowed (with); having;                     | 59404/dpd | ujugatāssa diṭṭhi, dhamme aveccappasādena {{samannāgato}}                    |
|                           | lit. going together [saṁ + anu + ā + √gam + ta]        |           |                                                                              |
| āgata (pp.)               | become; entered (into a state); pp. of āgacchati        | 11157/dpd | {{āgato}} imaṁ saddhamman”ti?                                               |

#+latex: \sentenceDiaSolution{./images/mn9-ayasma-sariputto-etadavoca.png}

\clearpage
\casesLegendHeaderBGHere

#+begin_quote
Katamaṁ panāvuso, nāmarūpaṁ, katamo nāmarūpasamudayo,

katamo nāmarūpanirodho, katamā nāmarūpanirodhagāminī paṭipadā?

Vedanā, saññā, cetanā, phasso, manasikāro — idaṁ vuccatāvuso, nāmaṁ;

cattāri ca mahābhūtāni, catunnañca mahābhūtānaṁ upādāyarūpaṁ

— idaṁ vuccatāvuso, rūpaṁ.
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo} H H
| vuccatāvuso            | is called, friend; sandhi. vuccati + āvuso                          | 69964/dpd | idaṁ {{vuccatāvuso}}, nāmaṁ                                      |
| upādāyarūpa (nt. +gen) | derived materiality (of) [upādāya + rūpa]                           | 16355/dpd | cattāri ca mahābhūtāni, catunnañca mahābhūtānaṁ {{upādāyarūpaṁ}} |
| upādāya (ind. +gen)    | derived (from); dependent (on); ger. of upādiyati; lit. taking near | 16351/dpd | cattāri ca mahābhūtāni, catunnañca mahābhūtānaṁ {{upādāya}}rūpaṁ |

#+latex: \sentenceDiaSolution{./images/mn9-katamam-panavuso-namarupam.png}

#+begin_quote
Iti idañca nāmaṁ idañca rūpaṁ — idaṁ vuccatāvuso, nāmarūpaṁ.

Viññāṇasamudayā nāmarūpasamudayo, viññāṇanirodhā nāmarūpanirodho,

ayameva ariyo aṭṭhaṅgiko maggo nāmarūpanirodhagāminī paṭipadā,

seyyathidaṁ — sammādiṭṭhi ... sammāsamādhi.

Yato kho, āvuso, ariyasāvako evaṁ nāmarūpaṁ pajānāti,

evaṁ nāmarūpasamudayaṁ pajānāti, evaṁ nāmarūpanirodhaṁ pajānāti,

evaṁ nāmarūpanirodhagāminiṁ paṭipadaṁ pajānāti,

so sabbaso rāgānusayaṁ pahāya, paṭighānusayaṁ paṭivinodetvā,

‘asmī’ti diṭṭhimānānusayaṁ samūhanitvā, avijjaṁ pahāya vijjaṁ uppādetvā,

diṭṭheva dhamme dukkhassantakaro hoti —

ettāvatāpi kho, āvuso, ariyasāvako sammādiṭṭhi hoti,

ujugatāssa diṭṭhi, dhamme aveccappasādena samannāgato, āgato imaṁ saddhamman”ti.
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo} H H
| pahāya (ger.)        | leaving behind; giving up; abandoning; ger of pajahati | 45098/dpd | so sabbaso rāgānusayaṁ {{pahāya}}, paṭighānusayaṁ paṭivinodetvā |
| paṭivinodeti         | drives out; dispels; removes; gets rid (of)            | 41040/dpd | so sabbaso rāgānusayaṁ pahāya, paṭighānusayaṁ {{paṭivinodetvā}} |
| samūhanati           | eradicates; kills off;                                 | 60144/dpd | ‘asmī’ti diṭṭhimānānusayaṁ {{samūhanitvā}}                      |
|                      | lit. kills up together [saṁ + ud + √han + a + ti]     |           |                                                                 |
| uppādeti             | generates; causes to arise; caus of uppajjati          | 16677/dpd | avijjaṁ pahāya vijjaṁ {{uppādetvā}}                            |
| antakara (adj. +gen) | makes an end (of); who puts an end (to) [anta + kara]  | 5650/dpd  | diṭṭheva dhamme dukkhass'{{antakaro}} hoti                      |

#+latex: \sentenceDiaSolution{./images/mn9-iti-idanca-namam.png}
#+latex: \sentenceDiaSolution{./images/mn9-yato-kho-avuso.png}
#+latex: \sentenceDiaSolution{./images/mn9-so-sabbaso-raganusayam.png}

\clearpage

*** Links                                                          :noexport:

[[https://www.tldraw.com/r/XXFsr0LAbq5hnpIPk68oZ?d=v-271.-85.1879.981.-MoEVvzvSGwo5y3S6Xo4B][tldraw: name-and-form (class)]]

[[https://www.tldraw.com/r/NBh0Ae8CWE1As8DiFaGI9?d=v-190.-177.1879.981.page][tldraw solved]]

list of ñānas, objectification, will experience the word

hypnotic suggestion

** SN 22.79 Khajjanīyasutta                                            :anki:

([[https://suttacentral.net/sn22.79/pli/ms][SC]], [[https://www.digitalpalireader.online/_dprhtml/index.html?loc=s.2.0.0.0.7.6.m][DPR]], [[http://localhost:4848/suttas/sn22.79/pli/ms?quote=Ki%25C3%25B1ca%252C%2520bhikkhave%252C%2520r%25C5%25ABpa%25E1%25B9%2581%2520vadetha%253F&window_type=Sutta+Study][SSP]], Sermon 10)

\casesLegendHeaderBGHere

#+begin_quote
Kiñca, bhikkhave, rūpaṁ vadetha?

Ruppatī'ti kho, bhikkhave, tasmā ‘rūpan’ti vuccati. Kena ruppati?

Sītenapi ruppati, uṇhenapi ruppati, jighacchāyapi ruppati, pipāsāyapi ruppati,
ḍaṁsa-makasa-vāt'ātapa-sarīsapa-samphassena-pi ruppati.

Ruppatī'ti kho, bhikkhave, tasmā ‘rūpan’ti vuccati. [...]
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo} H H
| ruppati           | is afflicted (by); is aggravated (by); is deformed (by) | 55132/dpd | {{Ruppatī}}'ti kho, bhikkhave, tasmā ‘rūpan’ti vuccati. |
| jighacchā (f.)    | hunger; lit. wanting to eat                             | 28439/dpd | {{jighacchāya}}'pi ruppati, pipāsāya'pi ruppati         |
| pipāsā (f. +loc.) | thirst (for)                                            | 46155/dpd | jighacchāya'pi ruppati, {{pipāsāya}}'pi ruppati         |

#+begin_quote
Tatra, bhikkhave, sutavā ariyasāvako iti paṭisañcikkhati:

‘Ahaṁ kho etarahi rūpena khajjāmi. Atītampāhaṁ addhānaṁ evameva rūpena khajjiṁ,

seyyathāpi etarahi paccuppannena rūpena khajjāmi.
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo} H H
| paṭisañcikkhati       | reflects; considers; discerns; syn. paccavekkhati                | 40815/dpd | Tatra, bhikkhave, sutavā ariyasāvako iti {{paṭisañcikkhati}} |
| etarahi (ind.)        | now; at present; lit. this day [eta + ahi]                       | 17887/dpd | Ahaṁ kho {{etarahi}} rūpena khajjāmi.                       |
| khajjati (pr. +instr) | is being eaten (by); is being nibbled (by); lit. is being chewed | 23289/dpd | Ahaṁ kho etarahi rūpena {{khajjāmi}}.                       |
| addhāna (nt.)         | time; period; extent                                             | 3017/dpd  | Atītampāhaṁ {{addhānaṁ}} evameva rūpena khajjiṁ             |

#+begin_quote
Ahañceva kho pana anāgataṁ rūpaṁ abhinandeyyaṁ,

anāgatampāhaṁ addhānaṁ evameva rūpena khajjeyyaṁ,

seyyathāpi etarahi paccuppannena rūpena khajjāmī’ti.

So iti paṭisaṅkhāya atītasmiṁ rūpasmiṁ anapekkho hoti; anāgataṁ rūpaṁ nābhinandati;

paccuppannassa rūpassa nibbidāya virāgāya nirodhāya paṭipanno hoti.
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo} H H
| paṭisaṅkhāya (ger.)  | reflecting; carefully considering                          | 40810/dpd | So iti {{paṭisaṅkhāya}} atītasmiṁ rūpasmiṁ anapekkho hoti               |
| anapekkha (adj.)     | indifferent (to); disinterested (in); lit. not looking out | 3717/dpd  | So iti paṭisaṅkhāya atītasmiṁ rūpasmiṁ {{anapekkho}} hoti               |
| paṭipanna (pp. +dat) | practising (for); lit. gone along                          | 40558/dpd | paccuppannassa rūpassa nibbidāya virāgāya nirodhāya {{paṭipanno}} hoti. |
|                      | [pati + √pad + na] pp of paṭipajjati                       |           |                                                                         |

*** Notes :noexport:

: (NP 14) Navaṁ pana bhikkhunā santhataṁ kārāpetvā chabbassāni dhāretabbaṁ. [...]

We only make blankets for ourselves every five or six years, even though our
children defecate and urinate on them and they are eaten by rats.”

#+begin_quote
Amhākaṁ pana sakiṁ katāni santhatāni pañcapi chapi vassāni honti,
yesaṁ no dārakā uhadantipi ummihantipi undūrehipi khajjanti.
#+end_quote

~khajjati~: chewed on:
resistance-impression, ~paṭighasamphassa~

*Nāma* and *rūpa*, as well as *paṭigha-* and *rūpasaññā*, are highly significant
terms. *Paṭigha-* and *rūpasaññā* are equivalent to *paṭighasamphassa* and
*adhivacanasamphassa* respectively. Now as to this perception of form, it is
basically conditioned by contact. That is why the *Kalahavivādasutta* states
that contact is the cause of the two views of existence and non-existence.

* 2025-01-22
** Exercise

#+latex: \renewcommand{\arraystretch}{1.6}

#+ATTR_LATEX: :center nil
| of the phenomenas (gen.pl. of dhamma)        | \fillin{5cm}{dhammānaṁ}   |
| by the sage (instr.sg. of muni)              | \fillin{5cm}{muninā}       |
| having seen (abs of √dis)                    | \fillin{5cm}{disvā}        |
| he taught (aor.sg. of desayati)              | \fillin{5cm}{desayi}       |
| having been delighted (by)                   | \fillin{5cm}{abhinanditvā} |
| he was released from (aor.sg. of muccati)    | \fillin{5cm}{mucci}        |
| they were released from (aor.pl. of muccati) | \fillin{5cm}{mucciṁsu}    |
| by the sickness (instr. of gelañña)          | \fillin{5cm}{gelaññena}    |

#+latex: \normalArrayStretch

** SN 46.16 Tatiyagilānasutta                                          :anki:

([[https://suttacentral.net/sn46.16/pli/ms][SC]], [[https://www.digitalpalireader.online/_dprhtml/index.html?loc=s.4.0.0.1.1.5.m][DPR]], [[http://localhost:4848/suttas/sn46.16/pli/ms?window_type=Sutta+Study][SSP]])

#+latex: \vspace*{-\baselineskip}

#+begin_quote
Ekaṁ samayaṁ bhagavā rājagahe viharati veḷuvane kalandakanivāpe.

Tena kho pana samayena bhagavā ābādhiko hoti dukkhito bāḷhagilāno.

Atha kho āyasmā mahācundo yena bhagavā tenupasaṅkami;

upasaṅkamitvā bhagavantaṁ abhivādetvā ekamantaṁ nisīdi.

Ekamantaṁ nisinnaṁ kho āyasmantaṁ mahācundaṁ bhagavā etadavoca:

“paṭibhantu taṁ, cunda, bojjhaṅgā”ti.
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo} H H
| paṭibhāti | comes to mind; occurs (to); lit. speaks back | 40689/dpd | {{paṭibhantu}} taṁ, cunda, bojjhaṅgā. |
| √bhā      | shine, speak                                 |           |                                       |

#+latex: \vspace*{-\baselineskip}
#+latex: \enlargethispage{\baselineskip}

#+begin_quote
“Sattime, bhante, bojjhaṅgā ...

“Taggha, cunda, bojjhaṅgā; taggha, cunda, bojjhaṅgā”ti.

Idamavocāyasmā cundo. Samanuñño satthā ahosi. Vuṭṭhahi ca bhagavā tamhā ābādhā.

Tathāpahīno ca bhagavato so ābādho ahosī'ti.
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo} H H
| samanuñña (adj.) | approving (of); consenting (to) | 59342/dpd | {{Samanuñño}} satthā ahosi. |
| satthā (m.)      | teacher; master; the Buddha     | 57894/dpd | Samanuñño {{satthā}} ahosi. |

\clearpage
\casesLegendHeaderBGHere

** Bojjhaṅga-paritta                                                   :anki:

#+begin_quote
Bojjhaṅgo sati-saṅkhāto / dhammānaṁ vicayo tathā

Viriyam-pīti-passaddhi / bojjhaṅgā ca tathā'pare

Samādh'upekkha-bojjhaṅgā / satt'ete sabba-dassinā

Muninā sammad-akkhātā / bhāvitā bahulīkatā

Saṁvattanti abhiññāya / nibbānāya ca bodhiyā

Etena sacca-vajjena / sotthi te hotu sabbadā
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo} H H
| saṅkhāta (pp.) | reckoned; so called; pp of saṅkhāyati | 56755/dpd | bojjhaṅgo sati-{{saṅkhāto}}                    |
| vicaya (m.)    | investigation; examination            | 67414/dpd | dhammānaṁ {{vicayo}} tathā                    |
| para (pron.)   | other; another                        | 42854/dpd | bojjhaṅgā ca tathā'{{pare}}                    |
| dassī (adj.)   | seeing; perceiving; knowing           | 32148/dpd | sabba-{{dassinā}}                              |
| muni (m.)      | monk; sage; seer                      | 53022/dpd | {{muninā}} sammad-akkhātā                      |
| vajja (ptp.)   | speaking; saying; ptp of vadati       | 65708/dpd | Etena sacca-{{vajjena}} sotthi te hotu sabbadā |

#+begin_quote
Ekasmiṁ samaye nātho / moggallānañ-ca kassapaṁ

Gilāne dukkhite disvā / bojjhaṅge satta desayi

Te ca taṁ abhinanditvā / rogā mucciṁsu taṅ-khaṇe

Etena sacca-vajjena / sotthi te hotu sabbadā
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo} H H
| nātha (m.)                | protector; lord; (The Buddha)                | 36192/dpd | Ekasmiṁ samaye {{nātho}}   |
| desayi (aor. +acc & +dat) | taught (to); explained (to); aor of desayati | 33981/dpd | bojjhaṅge satta {{desayi}}  |
| mucciṁsu (aor.3rd. +abl) | was released (from); aor of muccati          | 52830/dpd | rogā {{mucciṁsu}} taṅ-khaṇe |
| khaṇa (m.)                | moment; instant                              | 23317/dpd | rogā mucciṁsu taṅ-{{khaṇe}} |

\clearpage
\casesLegendHeaderBGHere

#+begin_quote
Ekadā dhamma-rājā pi / gelaññenābhipīḷito

Cundattherena tañ-ñeva / bhaṇāpetvāna sādaraṁ

Sammoditvā ca ābādhā / tamhā vuṭṭhāsi ṭhānaso

Etena sacca-vajjena / sotthi te hotu sabbadā
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo} H H
| divasa (m./nt.)       | day; from diva; √div (shine)                                    | 32680/dpd |                                                |
| gelañña (nt.)         | sickness; ill health; [√gilā + na + *ya]                        | 25212/dpd | {{gelaññenā}}bhipīḷito                         |
| abhipīḷita (pp.)      | affected; oppressed                                             | 7965/dpd  | gelaññen{{ābhipīḷito}}                         |
| taññeva (sandhi)      | that very; the self same [taṁ + eva]                           | 29303/dpd | Cundattherena {{taññeva}}                      |
| bhaṇāpeti (pr. caus.) | causes to speak; makes say; caus of bhaṇati                     | 49233/dpd | Cundattherena taññeva {{bhaṇāpetvāna}} sādaraṁ |
| sādaraṁ (ind.)       | with consideration; respectfully                                | 62172/dpd | bhaṇāpetvāna {{sādaraṁ}}                       |
| sammoditvā (abs.)     | having delighted together (with) [saṁ + √mud + *a + itvā]      | 60932/dpd | {{sammoditvā}} ca ābādhā                       |
| ṭhānaso (ind.)        | on the spot; right there; lit. from the place [√ṭhā + ana + so] | 29059/dpd | tamhā vuṭṭhāsi {{ṭhānaso}}                     |

#+begin_quote
Pahīnā te ca ābādhā / tiṇṇannam-pi mahesinaṁ

Magg'āhata-kilesā va / pattānuppatti-dhammataṁ

Etena sacca-vajjena / sotthi te hotu sabbadā
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo} H H
| tiṇṇaṁ / tiṇṇannaṁ (card.) | dat. or gen. of /ti/                                       | 30430/dpd | {{tiṇṇannam}}-pi mahesinaṁ  |
| mahesi (m.)                 | great sage; mighty seer; [mahā + isi]                      | 52091/dpd | tiṇṇannam-pi {{mahesinaṁ}}  |
| āhata (pp.)                 | struck; beaten; destroyed; [ā + √han + ta]                 | 13179/dpd | Magg'{{āhata}}-kilesā va     |
| patta (pp.)                 | reached; attained; accomplished; pp of pāpuṇāti            | 41851/dpd | {{pattā}}nuppatti-dhammataṁ |
| anuppatti (f.)              | non-arising; non-appearance; lit. not going up [ud + √pad] | 4906/dpd  | patt{{ānuppatti}}-dhammataṁ |
| dhammatā (f.)               | nature; characteristic; attribute                          | 34714/dpd | pattānuppatti-{{dhammataṁ}} |

*** Related                                                        :noexport:
**** Wheel 1 by Piyadassi Thera

https://www.accesstoinsight.org/lib/authors/piyadassi/wheel001.html

**** The Bojjhaṅgas: Medicine that Makes All Diseases Disappear (2008)

Chanmyay Myaing Sayadaw

The body is nāma-rūpa

p.5 [19]
: Cittena nīyati loko (SN 1.62)
: Taṇhāya nīyati loko (SN 1.63)

"The world is led around by consciousness / craving."

: “Cittena kho, bhikkhu, loko nīyati, cittena parikassati, cittassa uppannassa
: vasaṁ gacchatī”ti. (AN 4.186)

“Mendicant, the mind leads the world on. The mind drags it around. When the mind
arises, it takes control.”

Visuddhimagga Chapter XIV (Khandhāniddesa)

The body is four kinds of rūpa:

1. kammaja rūpa - kamma-produced form
2. cittaja rūpa - mind-produced form
3. utuja rūpa - temperature-produced form
4. āhāraja rūpa - nutriment-produced form

The bojjhaṅgas affect /cittaja rūpa/

[[http://localhost:4848/suttas/vb6/pli/ms?quote=r%25C5%25ABpa%25E1%25B9%2581%2520cittaja%25E1%25B9%2581&window_type=Sutta+Study][rūpaṁ cittajaṁ]]

... jivhāyatanassa upacayo, kāyāyatanassa upacayo, yaṁ vā panaññampi atthi rūpaṁ
cittajaṁ cittahetukaṁ cittasamuṭṭhānaṁ— idaṁ vuccati “rūpaṁ”. Iti idañca nāmaṁ,
idañca rūpaṁ. Idaṁ vuccati “viññāṇapaccayā nāmarūpaṁ”.

Story: Inge's Tumour (p.20 [34])

**** Visuddhimagga

Question: Where are these Pāli terms found:

kammaja rūpa, cittaja rūpa, utuja rūpa, āhāraja rūpa?

NORBU: These Pāli terms referring to the four types of matter (rūpa) according
to their origin are primarily found in the post-canonical Abhidhamma
commentarial literature, particularly in:

1. Visuddhimagga (The Path of Purification) by Buddhaghosa
2. Abhidhammatthasangaha (Manual of Abhidhamma) by Acariya Anuruddha

These terms describe the four ways material phenomena arise:

- kammaja rūpa: matter produced by kamma
- cittaja rūpa: matter produced by consciousness
- utuja rūpa: matter produced by temperature/heat
- āhāraja rūpa: matter produced by nutrition

The detailed analysis of these concepts is most extensively covered in the
Visuddhimagga's chapters on rūpa, particularly in Chapter XIV (Khandhāniddesa).

Since these are primarily commentarial terms rather than appearing in the
earliest Buddhist texts (Nikāyas), I should note that while I'm confident about
their presence in these later texts, you may want to verify the specific chapter
references I've provided.

[[http://localhost:4848/suttas/e0102n.mul/pli/cst4?quote=cittato%2520j%25C4%2581ta%25E1%25B9%2581%2520cittaja%25E1%25B9%2581&window_type=Sutta+Study][cittato jātaṁ cittajaṁ]]

#+begin_quote
(448.) puna sabbameva rūpaṁ sanidassanakammajādīnaṁ tikānaṁ vasena tividhaṁ
hoti. tattha oḷārike rūpaṁ sanidassanasappaṭighaṁ, sesaṁ anidassanasappaṭighaṁ.
sabbampi sukhumaṁ anidassanaappaṭighaṁ. evaṁ tāva sanidassanattikavasena
tividhaṁ. kammajādittikavasena pana kammato jātaṁ kammajaṁ, tadaññapaccayajātaṁ
akammajaṁ, nakutocijātaṁ neva kammajaṁ nākammajaṁ. cittato jātaṁ cittajaṁ,
tadaññapaccayajātaṁ acittajaṁ, nakutocijātaṁ neva cittajaṁ nācittajaṁ, āhārato
jātaṁ āhārajaṁ, tadaññapaccayajātaṁ anāhārajaṁ, nakutocijātaṁ neva āhārajaṁ
naanāhārajaṁ. ututo jātaṁ utujaṁ, tadaññapaccayajātaṁ anutujaṁ, nakutocijātaṁ
neva utujaṁ naanutujanti evaṁ kammajādittikavasena tividhaṁ.
#+end_quote
**** Bojjhanga Suttas chanted by small Sri Lankan boy Dhammaruwan

[[https://www.youtube.com/watch?v=ghyc9WftU3w][Bojjhanga Suttas chanted by small Sri Lankan boy - YouTube]]

*** Analysis                                                       :noexport:
**** Meter

Siloka (Śloka) meter

Boj/jhaṅ/go/ sa/ti/-saṅ/khā/to (8 syllables)
dham/mā/naṁ/ vi/ca/yo/ ta/thā (8 syllables)

**** Bojjhaṅgo sati-saṅkhāto

Line 1:
- Bojjhaṅgo: (nom. sing.) factor of enlightenment (bojjha + aṅga)
- sati-saṅkhāto: (nom. sing.) known as mindfulness (sati + saṅkhāta)
- dhammānaṁ: (gen. plural) of phenomena/states
- vicayo: (nom. sing.) investigation
- tathā: (adv.) likewise, thus

Line 2:
- viriyam: (nom. sing.) energy
- pīti: (nom. sing.) joy/rapture
- passaddhi: (nom. sing.) tranquility
- bojjhaṅgā: (nom. plural) factors of enlightenment
- ca: (conj.) and
- tathā: (adv.) likewise
- pare: (nom. plural) others

Line 3:
- samādhi: (nom. sing.) concentration
- upekkhā: (nom. sing.) equanimity
- bojjhaṅgā: (nom. plural) factors of enlightenment
- satta: (num.) seven
- ete: (dem. pron.) these
- sabba-dassinā: (inst. sing.) by the All-Seeing One

Line 4:
- muninā: (inst. sing.) by the sage
- sammad-akkhātā: (nom. plural) properly declared
- bhāvitā: (nom. plural) developed
- bahulīkatā: (nom. plural) practiced frequently

Line 5:
- saṁvattanti: (pres. 3rd plural) lead to
- abhiññāya: (dat. sing.) for direct knowledge
- nibbānāya: (dat. sing.) for Nibbāna
- ca: (conj.) and
- bodhiyā: (dat. sing.) for enlightenment

Line 6:
- etena: (inst. sing.) by this
- sacca-vajjena: (inst. sing.) truth utterance
- sotthi: (nom. sing.) well-being
- te: (dat. sing.) to you
- hotu: (imp. 3rd sing.) may there be
- sabbadā: (adv.) always

------

Ekasmiṁ samaye nātho
moggallānañ-ca kassapaṁ
Gilāne dukkhite disvā
bojjhaṅge satta desayi

1. Ekasmiṁ
- eka: "one" (numeral)
- smiṁ: locative case singular suffix
- Combined meaning: "at one, in one"

2. samaye
- samaya: "time, occasion"
- e: locative case singular suffix
- Meaning: "at time, on occasion"

3. nātho
- nātha: "protector, lord, refuge" (epithet of the Buddha)
- o: nominative case singular suffix
- Meaning: "the Lord"

4. moggallānañ-ca
- moggallāna: proper name (Moggallāna)
- ñ: accusative case marker
- ca: "and" (conjunction)
- Meaning: "Moggallāna and"

5. kassapaṁ
- kassapa: proper name (Kassapa)
- ṁ: accusative case singular suffix
- Meaning: "Kassapa" (as object)

6. Gilāne
- gilāna: "sick, ill"
- e: accusative case plural suffix
- Meaning: "the sick ones"

7. dukkhite
- dukkhita: "suffering, afflicted"
- e: accusative case plural suffix
- Meaning: "the afflicted ones"

8. disvā
- √dis: "to see"
- tvā: absolutive suffix
- Meaning: "having seen"

9. bojjhaṅge
- bojjhaṅga: "factor of enlightenment"
- e: accusative case plural suffix
- Meaning: "the factors of enlightenment"

10. satta
- "seven" (numeral)
- Meaning: "seven"

11. desayi
- √dis: "to teach, to preach"
- ayi: third person singular past tense suffix
- Meaning: "taught, preached"

Te ca taṁ abhinanditvā
rogā mucciṁsu taṅ-khaṇe

1. Te
- ta: demonstrative pronoun "they, those"
- e: nominative case plural suffix
- Meaning: "they"

2. ca
- conjunction "and"
- Meaning: "and"

3. taṁ
- ta: demonstrative pronoun "that"
- ṁ: accusative case singular suffix
- Meaning: "that" (referring to the teaching)

4. abhinanditvā
- abhi: prefix meaning "towards, thoroughly"
- √nand: "to rejoice, delight in"
- itvā: absolutive suffix
- Meaning: "having rejoiced in, having delighted in"

5. rogā
- roga: "disease, illness"
- ā: ablative case singular suffix
- Meaning: "from illness"

6. mucciṁsu
- √muc: "to release, to free"
- iṁsu: third person plural aorist suffix
- Meaning: "were freed, were released"

7. taṅ-khaṇe
- taṁ: "that"
- khaṇa: "moment, instant"
- e: locative case singular suffix
- Combined as compound: "at that moment"

**** Ekasmiṁ samaye nātho

Ekasmiṁ = in one (locative singular of eka)
samaye = time, occasion (locative singular)
nātho = protector, lord (nominative singular, referring to the Buddha)

moggallānañ-ca = and Moggallāna (accusative singular with conjunction -ca)
kassapaṁ = Kassapa (accusative singular)

gilāne = sick, ill (accusative plural)
dukkhite = suffering (accusative plural)
disvā = having seen (absolutive/gerund of √dis)
bojjhaṅge = factors of enlightenment (accusative plural)
satta = seven (numeral)
desayi = taught (aorist, 3rd person singular of √dis)

te = they (nominative plural)
ca = and
taṁ = that (accusative singular)
abhinanditvā = having rejoiced in (absolutive/gerund of abhi + √nand)
rogā = from disease (ablative singular)
mucciṁsu = were freed (aorist, 3rd person plural of √muc)
taṅ-khaṇe = at that moment (locative singular)

**** Ekadā dhamma-rājā pi

Ekadā = once, at one time (indeclinable)
dhamma-rājā = king of Dhamma (nominative singular compound)
pi = also, even (indeclinable particle)

gelaññena = by illness (instrumental singular)
abhipīḷito = oppressed, afflicted (past participle, nominative singular)

Cundattherena = by Elder Cunda (instrumental singular)
tañ-ñeva = that very same (accusative singular + emphatic particle eva)
bhaṇāpetvāna = having caused to recite (causative absolutive/gerund of √bhaṇ)
sādaraṁ = respectfully (adverb)

sammoditvā = having rejoiced (absolutive/gerund of sam + √mud)
ca = and
ābādhā = from illness (ablative singular)
tamhā = from that (ablative singular)
vuṭṭhāsi = arose, recovered (aorist, 3rd person singular of vuṭṭhāti)
ṭhānaso = immediately (indeclinable)

**** Pahīnā te ca ābādhā

Pahīnā = abandoned, eliminated (past participle, nominative plural)
te = those (nominative plural)
ca = and
ābādhā = illnesses (nominative plural)
tiṇṇannam-pi = of the three (genitive plural + emphatic particle pi)
mahesinaṁ = of the great sages (genitive plural)

magga = path (compound element)
āhata = struck, destroyed (past participle in compound)
kilesā = defilements (nominative plural)
va = like, just as, from iva (indeclinable particle)
pattā = attained (past participle, nominative plural)
anuppatti = non-arising (in compound)
dhammataṁ = state, nature (accusative singular)

**** Magg'āhata-kilesā va

The compound magg'āhata (where apostrophe indicates elision) means "struck/destroyed by the Path"

So the full phrase "Magg'āhata-kilesā va" means "like the defilements destroyed by the Path"

This is a powerful metaphorical comparison in the Bojjhanga Paritta. The line draws a parallel between:
- The way physical illnesses (ābādhā) were eliminated in the case of the three great sages
- How the Noble Path destroys mental defilements (kilesā)

**** pattānuppatti-dhammataṁ

(1) anuppatti -> an + uppatti -> an + ud + √pad + ti -> non-arising
(2) anuppatti -> from anupāpuṇāti -> anu + pa + √ap + ti -> attainment, realization (of)

√pad (go, step)
√ap (reach, attain)

1. patta = attained, reached (past participle of pāpuṇāti)
2. anuppatti = non-arising, non-occurrence (negative compound: an + uppatti)
- an = negative prefix
- uppatti = arising, rebirth, occurrence
3. dhammataṁ = state, nature, condition (accusative singular)

When combined, "pattānuppatti-dhammataṁ" means "reached/attained the state of
non-arising" or "attained the condition of non-recurrence."

For "pattānuppatti-dhammataṁ", I followed this construction:
patta + anuppatti + dhammataṁ
attained the non-arising / non-reoccurring state/condition
anuppatti as [an + ud + √pad]
√pad･3 ya (go, step)

Taking anuppatti as realized/attained [anu + pa + √ap + ti]
it would be "attained the attainment of the natural condition"?

Seems awkward for the double "attained", √ap root

saccānuppatti [sacca + anuppatti] takes that form

In the chanting reference I had this translation: "... just as defilements are demolished by the Path in accordance with step-by-step attainment."
going with √pad (go, step)

https://bhikkhu-manual.github.io/chants/parittas.html#awakening

step-by-step attainment (Wat Marp Jan)
https://youtu.be/IKUDUc__xsI?t=1312

reached the stage of never occurring again (Burmese)
https://youtu.be/G-U8n7--fyU?t=313

one attains what can be attained according to Dhamma (Chinese)
https://youtu.be/XizIU4qKoCk?t=212

On attaining the nature of non-arising
https://youtu.be/WqEh1fO6i0A?t=209

cease to arise forever (Singapore)
https://youtu.be/JHl9WhrqI6w?t=206

* 2025-01-15
** Exercise

#+latex: \renewcommand{\arraystretch}{1.6}

#+ATTR_LATEX: :center nil
| word          | pos            | meaning        |
|---------------+----------------+----------------|
| samayaṁ      | \fillin{3cm}{} | \fillin{5cm}{} |
| samayena      | \fillin{3cm}{} | \fillin{5cm}{} |
| rājagahe      | \fillin{3cm}{} | \fillin{5cm}{} |
| dukkhā        | \fillin{3cm}{} | \fillin{5cm}{} |
| nibbānāya     | \fillin{3cm}{} | \fillin{5cm}{} |
| viharati      | \fillin{3cm}{} | \fillin{5cm}{} |
| upasaṅkami    | \fillin{3cm}{} | \fillin{5cm}{} |
| upasaṅkamitvā | \fillin{3cm}{} | \fillin{5cm}{} |
| avoca         | \fillin{3cm}{} | \fillin{5cm}{} |
| saṁvattanti  | \fillin{3cm}{} | \fillin{5cm}{} |
| ahosi         | \fillin{3cm}{} | \fillin{5cm}{} |

#+latex: \normalArrayStretch

** SN 46.14 Paṭhamagilānasutta                                         :anki:

([[https://suttacentral.net/sn46.14/pli/ms][SC]], [[https://www.digitalpalireader.online/_dprhtml/index.html?loc=s.4.0.0.1.1.3.m][DPR]], [[http://localhost:4848/suttas/sn46.14/pli/ms?window_type=Sutta+Study][SSP]])

#+begin_quote
Ekaṁ samayaṁ bhagavā rājagahe viharati veḷuvane kalandakanivāpe.

Tena kho pana samayena āyasmā mahākassapo pippaliguhāyaṁ viharati

ābādhiko dukkhito bāḷhagilāno.
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo} H H
| veḷuvana (nt.)   | Bamboo Grove, a park outside Rājagaha [veḷu + vana]       | 70557/dpd | Ekaṁ samayaṁ bhagavā rājagahe viharati {{veḷuvane}} kalandakanivāpe.         |
| kalandaka (m.)   | squirrel                                                  | 20574/dpd | Ekaṁ samayaṁ bhagavā rājagahe viharati veḷuvane {{kalanda}}kanivāpe.         |
| nivāpa (m.)      | bait; fodder; feeding                                     | 38408/dpd | Ekaṁ samayaṁ bhagavā rājagahe viharati veḷuvane kalandaka{{nivāpe}}.         |
| pippaliguhā (f.) | lit. long pepper cave [pippali + guhā]                    | 46161/dpd | Tena kho pana samayena āyasmā mahākassapo {{pippaliguhāyaṁ}} viharati       |
| ābādhika (adj.)  | sick; ill; lit. oppressed                                 | 11993/dpd | āyasmā mahākassapo pippaliguhāyaṁ viharati {{ābādhiko}} dukkhito bāḷhagilāno |
| bāḷha (pp.)      | very strong; extreme; intense; lit. increased [√bah + ta] | 48406/dpd | āyasmā mahākassapo pippaliguhāyaṁ viharati ābādhiko dukkhito {{bāḷha}}gilāno |
| gilāna (adj.)    | sick; ill; unwell; lit. being sick                        | 24950/dpd | āyasmā mahākassapo pippaliguhāyaṁ viharati ābādhiko dukkhito bāḷha{{gilāno}} |

\clearpage
\casesLegendHeaderBGHere

#+begin_quote
Atha kho bhagavā sāyanhasamayaṁ paṭisallānā vuṭṭhito

yenāyasmā mahākassapo tenupasaṅkami; upasaṅkamitvā paññatte āsane nisīdi.

Nisajja kho bhagavā āyasmantaṁ mahākassapaṁ etadavoca:
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo} H H
| paṭisallāna (nt.)   | privacy; seclusion; solitude                   | 40862/dpd | Atha kho bhagavā sāyanhasamayaṁ {{paṭisallānā}} vuṭṭhito |
| vuṭṭhita (pp. +abl) | risen (from); got up (from); pp. of vuṭṭhahati | 70020/dpd | Atha kho bhagavā sāyanhasamayaṁ paṭisallānā {{vuṭṭhito}} |
|                     | [(v) + ud + √ṭhā + ita]                        |           |                                                         |
| paññatta (pp.)      | prepared; arranged; lit. caused to know;       | 39966/dpd | upasaṅkamitvā {{paññatte}} āsane nisīdi                 |
|                     | pp of paññāpeti, caus                          |           |                                                         |

#+begin_quote
“Kacci te, kassapa, khamanīyaṁ kacci yāpanīyaṁ?

Kacci dukkhā vedanā paṭikkamanti, no abhikkamanti;

paṭikkamosānaṁ paññāyati, no abhikkamo”ti?
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo} H H
| kacci (ind.)           | I hope; I trust                   | 19264/dpd | {{Kacci}} te, kassapa, khamanīyaṁ kacci yāpanīyaṁ?   |
| khamanīya (adj.)       | bearable; tolearable              | 23490/dpd | Kacci te, kassapa, {{khamanīyaṁ}} kacci yāpanīyaṁ?   |
| yāpanīya (adj.)        | able to keep going; sustainable   | 53983/dpd | Kacci te, kassapa, khamanīyaṁ kacci {{yāpanīyaṁ}}?   |
| paṭikkamati (pr. +abl) | returns (from); comes back (from) | 40244/dpd | Kacci dukkhā vedanā {{paṭikkamanti}}, no abhikkamanti |
| abhikkamati (pr.)      | goes forward; proceeds            | 7563/dpd  | Kacci dukkhā vedanā paṭikkamanti, no {{abhikkamanti}} |

#+begin_quote
“Na me, bhante, khamanīyaṁ, na yāpanīyaṁ. Bāḷhā me dukkhā vedanā abhikkamanti,

no paṭikkamanti; abhikkamosānaṁ paññāyati, no paṭikkamo”ti.

“Sattime, kassapa, bojjhaṅgā mayā sammadakkhātā;

bhāvitā bahulīkatā abhiññāya sambodhāya nibbānāya saṁvattanti. Katame satta?

Satisambojjhaṅgo kho, kassapa, mayā sammadakkhāto bhāvito bahulīkato

abhiññāya sambodhāya nibbānāya saṁvattati ... Ime kho, kassapa, satta bojjhaṅgā ...

“Taggha, bhagavā, bojjhaṅgā; taggha, sugata, bojjhaṅgā”ti.
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo} H H
| sammadakkhāta (adj.) | well taught; well preached [sammā + (d) + akkhāta] | 60730/dpd | Sattime, kassapa, bojjhaṅgā mayā {{sammadakkhātā}}; bhāvitā bahulīkatā |
| akkhāta (pp. +instr) | said (by); declared (by)                           | 399/dpd   | Sattime, kassapa, bojjhaṅgā mayā sammad{{akkhātā}}; bhāvitā bahulīkatā |
| bahulīkata (pp.)     | practised often; repeated a lot; [bahula + kata]   | 48190/dpd | Sattime, kassapa, bojjhaṅgā mayā sammadakkhātā; bhāvitā {{bahulīkatā}} |
| taggha (ind.)        | truly; definitely; lit. that indeed [tad + gha]    | 29228/dpd | {{Taggha}}, bhagavā, bojjhaṅgā                                         |

\clearpage
\casesLegendHeaderBGHere

#+begin_quote
Idamavoca bhagavā. Attamano āyasmā mahākassapo bhagavato bhāsitaṁ abhinandi.

Vuṭṭhahi cāyasmā mahākassapo tamhā ābādhā.

Tathāpahīno cāyasmato mahākassapassa so ābādho ahosī'ti.
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo} H H
| attamana (adj.)      | pleased; satisfied; lit. own mind [atta + mana] | 2524/dpd  | {{Attamano}} āyasmā mahākassapo bhagavato bhāsitaṁ abhinandi. |
| vuṭṭhahi (aor. +abl) | arose (from); got up (from); recovered (from)   | 69980/dpd | {{Vuṭṭhahi}} cāyasmā mahākassapo tamhā ābādhā.                 |
| tamhā (pron.)        | from that [ta + mhā] masc & nt abl sg of ta     | 30060/dpd | Vuṭṭhahi cāyasmā mahākassapo {{tamhā}} ābādhā.                 |
| pahīna (pp.)         | abandoned; dispelled; pp. of pajahati           | 45133/dpd | Tathā{{pahīno}} cāyasmato mahākassapassa so ābādho ahosī'ti.   |

*** Related                                                        :noexport:

mahā-kassapa-thera/dppn

One of the Buddha's most eminent disciples, chief among those who upheld minute
observances of form (dhutavādānam) (A.i.23). He was born in the brahmin village
of Mahātittha in Magadha, and was the son of the brahmin Kapila, his mother
being Sumanādevī; he himself was called Pippali. At Ap.ii.583, vs. 56; but there
his father is called Kosiyagotta.

pippaliguhāya-1/comm

: pippaliguhāyanti tassā kira guhāya dvārasamīpe eko pippalirukkho ahosi,
: tena sā pippaliguhā'ti paññāyittha.

'Pipphali Cave' - near the entrance of that cave there was, they say, a long
pepper (pippali) tree. Because of that, it was known as 'Pipphali Cave'.

** SN 46.15 Dutiyagilānasutta                                          :anki:

([[https://suttacentral.net/sn46.15/pli/ms][SC]], [[https://www.digitalpalireader.online/_dprhtml/index.html?loc=s.4.0.0.1.1.4.m][DPR]], [[http://localhost:4848/suttas/sn46.15/pli/ms?window_type=Sutta+Study][SSP]])

#+begin_quote
Ekaṁ samayaṁ bhagavā rājagahe viharati veḷuvane kalandakanivāpe.
Tena kho pana samayena āyasmā mahāmoggallāno gijjhakūṭe pabbate viharati
ābādhiko dukkhito bāḷhagilāno.
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo} H H
| gijjhakūṭa (m.) | Vulture's Peak [gijjha + kūṭa] | 24890/dpd | āyasmā mahāmoggallāno {{gijjhakūṭe}} pabbate viharati |
| pabbata (m.)    | rock; mountain; hill           | 42495/dpd | āyasmā mahāmoggallāno gijjhakūṭe {{pabbate}} viharati |

*Bojjhaṅga-paritta:*

#+begin_quote
Ekasmiṁ samaye nātho

moggallānañ-ca kassapaṁ

Gilāne dukkhite disvā

bojjhaṅge satta desayi

Te ca taṁ abhinanditvā

rogā mucciṁsu taṅkhaṇe

Etena sacca-vajjena

sotthi te hotu sabbadā
#+end_quote

* 2025-01-08
** Declension Cases Overview

#+ATTR_LATEX: :center nil
| 1. Nominative   | subject performing the action       | Who is giving?                |
| 2. Accusative   | direct object                       | What is he/she giving?        |
| 3. Instrumental | means, instrument                   | With/by/through what?         |
| 4. Dative       | indirect object, recipient, purpose | To whom? For what?            |
| 5. Ablative     | motion/separation from, comparison  | From where? Better than what? |
| 6. Genitive     | possession, relationship            | Whose?                        |
| 7. Locative     | location, time                      | Where? When?                  |
| 8. Vocative     | direct address                      | Form, bhikkhus, is not-self.  |

#+latex: \bigskip {\centering
#+latex: Mnemonics:
#+latex: \par}

| 1. *Nominate* who will do it.      | 5. Pieces fall from the *ablative* heat-shield. |
| 2. Give an objective *accusation*. | 6. The *genitive* glues possessions to people.  |
| 3. Fix it with this *instrument*.  | 7. *Locate* him in space and time.              |
| 4. *Donate* a date to him.         | 8. Shout a *vocal* address.                     |

Origin of the word "Dative":

| PIE root:      | /√do-/ to give                                                   |
| Latin:         | /donum/ gift, /donatio/ a giving, /dativus/ pertaining to giving |
| Pāli/Sanskrit: | /dadāti/ gives [√dā + dā + a → dadā]                             |

Origin of the word "Ablative":

| Latin   | PIE      | Pāli/Sanskrit    |                   |                                 |
| /ab-/   | /√apo/   | /apa-/           | off, away from    | apocalypse, apology, apostle    |
| /ferre/ | /√bher-/ | /√bhar/ / /√bhṛ/ | to carry, to bear | birth, bring, burden,           |
|         |          |                  |                   | differ, offer, suffer, transfer |

\clearpage

** Cases Exercise: The Elephant

\casesLegendHeaderBGHere

#+begin_quote
Jetavane hatthinī soṇḍāya vā dīghahatthena vā

attano hatthipotakassa tiṇaṁ datvā,

tato soṇḍato mahāsaddaṁ pahiṇi.

Imassa hatthipotakassa tiṇena kucchi mahanto ahosi.
#+end_quote

# At Jetavana, the elephant gave grass to her own baby-elephant by the trunk (or by the long hand),
# then sent a loud noise from the trunk.
# The belly of this baby elephant grew large with grass.

\bigskip

| hatthinī (f.) | female elephant [hatthī + inī] | pahiṇi (aor.)  | sent; aor. of pahiṇāti    |
| soṇḍā (f.)    | elephant's trunk               | kucchi (m.)    | stomach; belly            |
| hattha (m.)   | hand                           | mahanta (adj.) | big; large                |
| potaka (m.)   | young animal                   | ahosi (aor.)   | was; became; aor. of hoti |
| tiṅa (nt.)    | grass; straw                   |                |                           |

#+latex: \enlargethispage{\baselineskip}
#+latex: \renewcommand{\arraystretch}{1.6}

| word             | meaning                            | case                |
|------------------+------------------------------------+---------------------|
| Jetavane         | \fillin{5cm}{at Jetavana}          | \fillin{3cm}{loc.}  |
| hatthinī         | \fillin{5cm}{the female elephant}  | \fillin{3cm}{nom.}  |
| soṇḍāya vā       | \fillin{5cm}{by the trunk}         | \fillin{3cm}{inst.} |
| dīghahatthena vā | \fillin{5cm}{or by the long hand}  | \fillin{3cm}{inst.} |
| attano           | \fillin{5cm}{her own}              | \fillin{3cm}{gen.}  |
| hatthipotakassa  | \fillin{5cm}{to the baby-elephant} | \fillin{3cm}{dat.}  |
| tiṇaṁ           | \fillin{5cm}{grass}                | \fillin{3cm}{acc.}  |
| datvā            | \fillin{5cm}{having given}         | \fillin{3cm}{ger.}  |
| tato            | \fillin{5cm}{then}                  | \fillin{3cm}{ind.}    |
| soṇḍato         | \fillin{5cm}{from the trunk}        | \fillin{3cm}{abl.}    |
| mahāsaddaṁ     | \fillin{5cm}{a loud noise}          | \fillin{3cm}{acc.}    |
| pahiṇi          | \fillin{5cm}{sent (→ pahiṇāti)}     | \fillin{3cm}{aor.}    |
| imassa          | \fillin{5cm}{pron. of this (→ ima)} | \fillin{3cm}{gen.sg.} |
| hatthipotakassa | \fillin{5cm}{of the baby elephant}  | \fillin{3cm}{gen.}    |
| tiṇena          | \fillin{5cm}{with grass}            | \fillin{3cm}{inst.}   |
| kucchi          | \fillin{5cm}{belly, stomach}        | \fillin{3cm}{nom.}    |
| mahanto         | \fillin{5cm}{adj. great, large}     | \fillin{3cm}{nom.}    |
| ahosi           | \fillin{5cm}{was, became (→ hoti)}  | \fillin{3cm}{aor.}    |

#+latex: \normalArrayStretch

\clearpage

** AN 10.81 Vāhanasutta, The lotus simile to Vāhana                    :anki:
:PROPERTIES:
:DECK_NAME: AN 10.81 Vāhanasutta
:END:

\casesLegendHeaderBGHere

([[https://suttacentral.net/an10.81/pli/ms][SC]], [[https://www.digitalpalireader.online/_dprhtml/index.html?loc=a.9.0.0.1.3.0.m][DPR]], [[http://localhost:4848/suttas/an10.81/pli/ms?window_type=Sutta+Study][SSP]], Sermon 18)

#+begin_quote
Ekaṁ samayaṁ bhagavā campāyaṁ viharati gaggarāya pokkharaṇiyā tīre.

Atha kho āyasmā vāhano yena bhagavā tenupasaṅkami;

upasaṅkamitvā bhagavantaṁ abhivādetvā ekamantaṁ nisīdi.

Ekamantaṁ nisinno kho āyasmā vāhano bhagavantaṁ etadavoca:
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo} H H
| pokkhara (nt.)                    | blue lotus flower                      | 47383/dpd | Ekaṁ samayaṁ bhagavā campāyaṁ viharati gaggarāya {{pokkharaṇiyā}} tīre. |
| tīra (nt.)                        | shore, riverbank                       | 30918/dpd | Ekaṁ samayaṁ bhagavā campāyaṁ viharati gaggarāya pokkharaṇiyā {{tīre}}. |
| yena ... ten'upasaṅkamati (idiom) | wherever ... he approaches (him/it)    | 31234/dpd | Atha kho āyasmā vāhano yena bhagavā {{tenupasaṅkami}}                    |
| abhivādeti                        | bows down (to); pays high respect (to) | 8333/dpd  | upasaṅkamitvā bhagavantaṁ {{abhivādetvā}} ekamantaṁ nisīdi.             |
| ekamantaṁ (ind.)                 | to one side; aside [ekaṁ + anta + aṁ] | 17613/dpd | upasaṅkamitvā bhagavantaṁ abhivādetvā {{ekamantaṁ}} nisīdi.             |
| nisīdati                          | sits (on); sits down                   | 38204/dpd | upasaṅkamitvā bhagavantaṁ abhivādetvā ekamantaṁ {{nisīdi}}.             |
| avoca (aor.)                      | said (to); aor. of vacati              | 10795/dpd | āyasmā vāhano bhagavantaṁ etad{{avoca}}                                 |

#+begin_quote
“Katihi nu kho, bhante, dhammehi tathāgato nissaṭo visaṁyutto vippamutto

vimariyādīkatena cetasā viharatī”ti?
#+end_quote

# Detached, disengaged and released from how many things does the Tathāgata
# dwell with an unrestricted mind?

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo} H H
| kati (interr.)         | how many?                                      | 19695/dpd | {{Katihi}} nu kho, bhante, dhammehi tathāgato nissaṭo                        |
| nissaṭa (pp. +abl)     | escaped (from), freed (from); pp. of nissarati | 38271/dpd | tathāgato {{nissaṭo}} visaṁyutto vippamutto vimariyādīkatena cetasā viharati |
| visaṁyutta (pp. +abl) | detached (from)                                | 69208/dpd | tathāgato nissaṭo {{visaṁyutto}} vippamutto vimariyādīkatena cetasā viharati |
| vippamutta (pp. +abl)  | released (from)                                | 68475/dpd | tathāgato nissaṭo visaṁyutto {{vippamutto}} vimariyādīkatena cetasā viharati |
| vimariyādīkata (adj.)  | unbounded [vi + mariyādā + kata]               | 68663/dpd | tathāgato nissaṭo visaṁyutto vippamutto {{vimariyādīkatena}} cetasā viharati |
| mariyādā (f.)          | boundary, border, limit                        | 51492/dpd | tathāgato nissaṭo visaṁyutto vippamutto vi{{mariyādī}}katena cetasā viharati |

#+begin_quote
“Dasahi kho, vāhana, dhammehi tathāgato nissaṭo visaṁyutto vippamutto vimariyādīkatena

cetasā viharati. Katamehi dasahi? Rūpena kho, vāhana, tathāgato nissaṭo visaṁyutto

vippamutto vimariyādīkatena cetasā viharati, vedanāya ... saññāya ... saṅkhārehi ... viññāṇena

... jātiyā ... jarāya ... maraṇena ... dukkhehi ... kilesehi kho, vāhana, tathāgato nissaṭo

visaṁyutto vippamutto vimariyādīkatena cetasā viharati.
#+end_quote

\clearpage
\casesLegendHeaderBGHere

#+begin_quote
Seyyathāpi, vāhana, uppalaṁ vā padumaṁ vā puṇḍarīkaṁ vā

udake jātaṁ udake saṁvaḍḍhaṁ udakā paccuggamma ṭhitaṁ anupalittaṁ udakena;

evamevaṁ kho, vāhana, imehi dasahi dhammehi tathāgato nissaṭo visaṁyutto

vippamutto vimariyādīkatena cetasā viharatī”ti.
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo} H H
| uppala, paduma, puṇḍarīka (nt.) | types of lotus                                           | 16618/dpd | Seyyathāpi, vāhana, {{uppalaṁ}} vā padumaṁ vā puṇḍarīkaṁ vā                               |
| udaka (nt.)                     | water                                                    | 14832/dpd | {{udake}} jātaṁ {{udake}} saṁvaḍḍhaṁ {{udakā}} paccuggamma ṭhitaṁ anupalittaṁ {{udakena}} |
| saṁvaḍḍha (pp.)                | grown up (in); fully grown (in) [saṁ + √vaḍḍh + ta]     | 61844/dpd | udake jātaṁ udake {{saṁvaḍḍhaṁ}} udakā paccuggamma ṭhitaṁ anupalittaṁ udakena             |
| paccuggamma (ger. +abl)         | going out (from), emerging (from); ger of paccuggacchati | 39489/dpd | udake jātaṁ udake saṁvaḍḍhaṁ udakā {{paccuggamma}} ṭhitaṁ anupalittaṁ udakena             |
| tiṭṭhati                        | stands                                                   | 30486/dpd | udake jātaṁ udake saṁvaḍḍhaṁ udakā paccuggamma {{ṭhitaṁ}} anupalittaṁ udakena             |
| anupalitta (pp. +instr)         | not smeared (by), untainted (by); [na + upalitta]        | 4747/dpd  | udake jātaṁ udake saṁvaḍḍhaṁ udakā paccuggamma ṭhitaṁ {{anupalittaṁ}} udakena             |

** MN 112, The bhikkhu with defilements ended

(See also: Nibbāna Sermon 15)

#+begin_quote
Khīṇāsavassa, bhikkhave, bhikkhuno ... veyyākaraṇāya:

"Diṭṭhe kho ahaṁ, āvuso, anupāyo anapāyo anissito appaṭibaddho vippamutto
visaṁyutto vimariyādīkatena cetasā viharāmi."

"Sute ... mute ... viññāte ..."
#+end_quote

# Friends, with regard to the seen, I dwell unattracted, unrepelled,
# independent, uninvolved, released, unshackled, with a mind free from barriers.

*** Related                                                        :noexport:

nissaṭa (pp of nissarati)
nissaraṇa (nt.):
Synonym: mutta, vippamutta
Comm: nissaraṇan'ti nissaṭabhāvaṁ.

vippamutta (pp of vipamuccati)
Synonym: nissaṭa, mutta
Comm: vippamuttā'ti rāg'ādīhi vippamuttā.

visaṁyutta [vi + saṁ + √yuj + ta]
Synonym: anissita, asāratta
Iti 112: sabbalokavisaṁyutta

saṁyojana [saṁ + √yuj + *e + ana]
bhavasaṁyojana

anupalitta (pp of na upalimpati)
Comm: anupalittassā'ti taṇhādiṭṭhikilesehi alittassa.
Iti 76: alittam'upalimpati

Ud 2.4, Sakkārasutta, Sermon 17

Phusanti phassā upadhiṁ paṭicca,
Nirupadhiṁ kena phuseyyum phassā.

Touches touch one because of assets,
How can touches touch him who is asset-less?

> *Iti ajjhattaṁ vā kāye kāyānupassī viharati, bahiddhā vā kāye kāyānupassī
> viharati, ajjhattabahiddhā vā kāye kāyānupassī viharati; samudayadhammānupassī
> vā kāyasmiṁ viharati, vayadhammānupassī vā kāyasmiṁ viharati,
> samudayavayadhammānupassī vā kāyasmiṁ viharati; 'atthi kāyo'ti vā pan'assa
> sati paccupaṭṭhitā hoti, yāvadeva ñāṇamattāya paṭissatimattāya; anissito ca
> viharati, na ca kiñci loke upādiyati*.[^fn145]
>
> In this way he abides contemplating the body as a body internally, or he

DN 22 / MN 10

> *Passati Bhagavā cakkhunā rūpaṁ, chandarāgo Bhagavato natthi, suvimuttacitto
> Bhagavā.*[^fn611]
>
> The Exalted One sees forms with the eye, but there is no desire or attachment
> in him, well freed in mind is the Exalted One.

[^fn611]: S IV 164, *Koṭṭhikasutta*

> *Evaṁ sammā vimuttacittassa kho, āvuso, bhikkhuno bhusā cepi cakkhuviññeyyā
> rūpā cakkhussa āpāthaṁ āgacchanti, nevassa cittaṁ pariyādiyanti,
> amissīkatamevassa cittaṁ hoti ṭhitaṁ āneñjappattaṁ, vayaṁ cassānupassati*.
> *Bhusā cepi sotaviññeyyā saddā ... bhūsa cepi ghānaviññeyyā gandhā ... bhūsa
> cepi jivhāviññeyyā rasā ... bhūsa cepi kāyaviññeyyā phoṭṭhabbā ... bhūsa cepi
> manoviññeyyā dhammā manassa āpāthaṁ āgacchanti, nevassa cittaṁ pariyādiyanti,
> amissīkatamevassa cittaṁ hoti ṭhitaṁ āneñjappattaṁ, vayaṁ
> cassānupassati*.[^fn613]
>
> Friend, in the case of a monk who is fully released, even if many forms
> cognizable by the eye come within the range of vision, they do not overwhelm
> his mind, his mind remains unalloyed, steady and unmoved, he sees its passing
> away. Even if many sounds cognizable by the ear come within the range of
> hearing ... even if many smells cognizable by the nose ... even if many tastes
> cognizable by the tongue ... even if many tangibles cognizable by the body ...
> even if many mind-objects cognizable by the mind come within the range of the
> mind, they do not overwhelm his mind, his mind remains unalloyed, steady and
> unmoved, he sees its passing away.

[^fn613]: A IV 404, *Silāyūpasutta*

* 2024-12-27                                                       :noexport:
** Ratana sutta: khīṇaṁ purāṇaṁ...

#+begin_quote
Khīṇaṁ purāṇaṁ navaṁ natthi sambhavaṁ,

Viratta- cittāyatike bhavasmiṁ;

Te khīṇa- bījā avirūḷhi- chandā,

Nibbanti dhīrā yathā- yaṁ padīpo;

Idampi saṅghe ratanaṁ paṇītaṁ,

Etena saccena suvatthi hotu.
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo}
| khīyati                       | is destroyed; is exhausted                                 |
| khīṇa (pp. of khīyati)         | consumed; destroyed                                        |
| khaya (m. from khīyati)       | wearing away; destruction                                  |
| purāṇa (adj.)                  | previous; old; ancient                                     |
| nava (adj.)                   | new; fresh                                                 |
| sambhavati                    | comes to be; happens; occurs                               |
| sambhava (m. from sambhavati) | birth; origin; source (of)                                 |
| rajjati                       | finds pleasure (in); is enamoured (with)                   |
| virajjati                     | becomes detached (from); loses interest (in)               |
| viratta (pp. of virajjati)    | detached (from); without desire (for); lost interest (in)  |
| āyati (f.)                    | future; upcoming                                           |
| āyatika (adj. from āyati)     | upcoming; future                                           |
| bīja (nt.)                    | seed; germ                                                 |
| virūḷhi (f.)                   | growth; increase                                           |
| chanda (m.)                   | (1) interest; desire; wish (2) consent; agreement          |
| nibbāti                       | is extinguished; goes out; lit. blows away                 |
| dhīra (adj.)                  | (1) stable; constant; reliable; firm (2) wise; intelligent |
| padīpa (m.)                   | lamp; light; lighting                                      |

(tesaṁ,) purāṇaṁ kammaṁ khīṇaṁ hoti

navaṁ sambhavaṁ natthi

kammaṁ: nt. nom/acc. sg.

kammaṁ khettaṁ, viññāṇaṁ bījaṁ, taṇhā sneho (AN 3.76)

*** Links                                                          :noexport:

[[http://localhost:4848/suttas/snp2.1/pli/ms?quote=Kh%25C4%25AB%25E1%25B9%2587a%25E1%25B9%2581%2520pur%25C4%2581%25E1%25B9%2587a%25E1%25B9%2581&window_type=Sutta+Study][Khīṇaṁ purāṇaṁ...]]

[[https://www.tldraw.com/r/hXdaGU7vKip5vHbAkQa8D?d=v-278.-199.1553.811.page][tldraw board]]

*** Analysis                                                       :noexport:

Provide a word-by-word grammar analysis of the following Pali text.
Indicate omitted subjects, objects or verbs (e.g. hoti).

: Khīṇaṁ purāṇaṁ navaṁ natthi sambhavaṁ,
: Virattacittāyatike bhavasmiṁ;

The construction follows a parallel structure:
[tesaṁ] khīṇaṁ purāṇaṁ [hoti] - "the old is destroyed [for them]"

Khīṇaṁ:
- Root: √khī (to waste away, be exhausted)
- Past participle of khīyati
- Nominative/accusative singular neuter
- Meaning: exhausted, destroyed

purāṇaṁ:
- Adjective
- Nominative/accusative singular neuter
- Meaning: old, former

navaṁ:
- Adjective
- Nominative/accusative singular neuter
- Meaning: new

natthi:
- na (negative particle) + atthi (from √as, to be)
- 3rd person singular present indicative
- Meaning: is not, does not exist

sambhavaṁ:
- Prefix saṁ + √bhū (to become)
- Nominative/accusative singular neuter
- Action noun/gerund
- Meaning: arising, origination

Viratta-cittāyatike:
- Compound word (tatpurusa):
  * viratta: past participle of virajjati (vi + √raj)
  * citta: mind
  * āyatika: future, what lies ahead
- Locative singular
- Meaning: in future becoming

bhavasmiṁ:
- Root: √bhū (to become)
- Locative singular masculine
- Meaning: in existence

: Te khīṇabījā avirūḷhichandā,
: Nibbanti dhīrā yathāyaṁ padīpo;

Te:
- Demonstrative pronoun, nominative plural masculine
- "They, those"

khīṇabījā:
- Compound adjective (bahuvrīhi), nominative plural masculine
- khīṇa (destroyed) + bīja (seed)
- "Those whose seeds are destroyed"

avirūḷhichandā:
- Compound adjective (bahuvrīhi), nominative plural masculine
- a (negative) + virūḷhi (growth) + chanda (desire)
- "Those whose desire for growth has ceased"

Nibbanti:
- Verb, 3rd person plural present indicative
- Root: √nibbā (to be extinguished)
- "They are extinguished"

dhīrā:
- Adjective/noun, nominative plural masculine
- "The wise ones"

yathā:
- Indeclinable, adverb of comparison
- "Just as, like"

ayaṁ:
- Demonstrative pronoun, nominative singular masculine
- "This"

padīpo:
- Noun, nominative singular masculine
- "Lamp"
* Dhammapada 21-23                                                 :noexport:
** Chanting: Yaṅkiñci ratanaṁ loke

#+begin_quote
Yaṅkiñci ratanaṁ loke vijjati

vividhaṁ puthu ratanaṁ buddhasamaṁ natthi

tasmā sotthī bhavantu te
#+end_quote

\vspace*{2\baselineskip}

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo}
| vividha (adj.)   | various kinds of; assorted; multiple |
| puthu (ind.)     | far and wide; all over               |
| sama (adj.)      | level; even; balanced                |
| sama (nt.)       | similarity; equality                 |
| sotthi (f. +dat) | safety (for); well-being (for)       |
|                  | abstr, from atthi (+dat)             |

** Dhammapada: Sāmāvatīvatthu (Dhp 21-23)

#+begin_quote
Appamādo amatapadaṁ,

pamādo maccuno padaṁ;

Appamattā na mīyanti,

ye pamattā yathā matā.
#+end_quote

\vspace*{2\baselineskip}

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo}
| appamāda (m.) | lit. not heedless; [na + pamajjati] |
| maccu (m.)    | death                               |
| mīyati        | is killed; dies; pass of marati     |

\clearpage
\casesLegendHeaderBGHere

#+begin_quote
Evaṁ visesato ñatvā,

appamādamhi paṇḍitā;

Appamāde pamodanti,

ariyānaṁ gocare ratā.
#+end_quote

\vspace*{2\baselineskip}

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo}
| visesato (ind.)     | distinctly; clearly                          |
| pamodati (pr. +loc) | is delighted (with/about)                    |
| gocara (m.)         | food; grazing; pasture                       |
|                     | lit. (where the) cows walk [go + cara]       |
| rata (pp. +loc)     | pleased (with/about); enjoying; pp of ramati |

#+begin_quote
Te jhāyino sātatikā,

niccaṁ daḷhaparakkamā;

Phusanti dhīrā nibbānaṁ,

yogakkhemaṁ anuttaraṁ.
#+end_quote

\vspace*{2\baselineskip}

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo}
| jhāyī (adj.)          | meditating; contemplating; from jhāyati       |
| sātatika (adj.)       | persevering; consistent                       |
| daḷhaparakkama (adj.) | making continuous effort; [daḷha + parakkama] |
| daḷha (pp.)           | firm; steady; strenuous                       |
| phusati               | touches; contacts; feels; experiences         |
| yoga (m.)             | yoke; bond; attachment                        |

*** Links                                                          :noexport:

[[http://localhost:4848/suttas/dhp21-32/pli/ms?quote=Appam%25C4%2581do%2520amatapada%25E1%25B9%2581&window_type=Sutta+Study][Dhp 21]]
* Pārājika 4                                                       :noexport:
** Exercise

#+begin_quote
Yasmā ca kho bhikkhave

\vin atthi ajātaṁ abhūtaṁ akataṁ asaṅkhataṁ

Tasmā jātassa bhūtassa katassa saṅkhatassa

\vin nissaraṇaṁ paññāyati.
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo}
| paññāyati | is clearly known; is evident; pass. of pajānāti |

#+begin_quote
Yan-dunnimittaṁ avamaṅgalañ-ca, yo cāmanāpo sakuṇassa saddo

Pāpaggaho dussupinaṁ akantaṁ, buddhānubhāvena vināsamentu
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo}
| gaha (m.)     | (1) grip; grabbing; from gaṇhāti  |
|               | (2) planet; lit. what is grasped  |
| ānubhāva (m.) | power; ability                    |
| vināsa (m.)   | destruction; ruin; from vinassati |
| eti (+acc)    | comes (to); goes (to); becomes     |

\vspace*{2\baselineskip}

** Pārājika 4

#+begin_quote
Yo pana bhikkhu anabhijānaṁ uttari-manussa-dhammaṁ

attūpanāyikaṁ alam-ariya-ñāṇa-dassanaṁ samudācareyya

“iti jānāmi, iti passāmī”ti.
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo}
| attūpanāyika (adj.) | referring to oneself [atta + upanāyika] |
| samudācarati        | asserts; announces                      |

\clearpage
\casesLegendHeaderBGHere

#+begin_quote
Tato aparena samayena

samanuggāhiyamāno vā asamanuggāhiyamāno vā

āpanno visuddhāpekkho evaṁ vadeyya,
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo}
| apara (adj.)                    | another; after                                       |
| samaya (m.)                     | time; occasion                                       |
| āpanna (pp. + acc.)             | fallen into; pp. of āpajjati                         |
| samanuggāhiyamāna (prp. +instr) | being closely questioned (by); lit. being dived into |
|                                 | [saṁ + anu + √gāh + īya + māna]                     |
| apekkha (adj.)                  | looking (for); desiring                              |

\vspace*{2\baselineskip}

#+begin_quote
“Ajānam-evaṁ āvuso avacaṁ 'jānāmi', apassaṁ 'passāmi'.

Tucchaṁ musā vilapi”nti.

Aññatra adhimānā: ayam-pi pārājiko hoti asaṁvāso.
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo}
| tucchaṁ (ind.) | emptily; vainly; without substance [tuccha + aṁ] |
| musā (ind.)     | falsely; untruthfully                             |
| vilapi          | talked nonsense; aor. of vilapati                 |

*** Links                                                          :noexport:

[[http://localhost:4848/suttas/pli-tv-bu-pm/pli/ms?quote=Yo%2520pana%2520bhikkhu%2520anabhij%25C4%2581na%25E1%25B9%2581&window_type=Sutta+Study][Pr 4 (SSP)]]

** Closing of Pr 4                                                 :noexport:

#+begin_quote
Uddiṭṭhā kho āyasmanto cattāro pārājikā dhammā,

yesaṁ bhikkhu aññataraṁ vā aññataraṁ vā āpajjitvā

na labhati bhikkhūhi saddhiṁ saṁvāsaṁ.

Yathā pure, tathā pacchā: pārājiko hoti asaṁvāso.
#+end_quote

#+begin_quote
Tatth'āyasmante pucchāmi: kacci'ttha parisuddhā?

Dutiyampi ... tatiyampi ...

Parisuddh'etth'āyasmanto, tasmā tuṇhī,

evam-etaṁ dhārayāmi.
#+end_quote

* Name-and-Form                                                    :noexport:
** Cases Exercise: The Elephant

\casesLegendHeaderBGHere

#+begin_quote
Jetavane hatthinī soṇḍāya vā dīghahatthena vā

attano hatthipotakassa tiṇaṁ datvā,

tato vīriyārambhāya soṇḍato mahāsaddaṁ pahiṇi.

Imassa hatthipotakassa tiṇena kucchi mahanto ahosi.
#+end_quote

# At Jetavana, the elephant gave grass to her own baby-elephant by the trunk (or by
# the long hand), then sent a loud noise from the trunk for making effort.
# The belly of this baby elephant grew large with grass.

#+latex: \vspace*{2\baselineskip}
#+latex: \renewcommand{\arraystretch}{1.6}

#+ATTR_LATEX: :environment longtable :align L{4cm} L{5cm} L{3cm}
| word             | meaning                             | case                  |
|------------------+-------------------------------------+-----------------------|
| Jetavane         | \fillin{5cm}{at Jetavana}           | \fillin{3cm}{loc.}    |
| hatthinī         | \fillin{5cm}{the female elephant}   | \fillin{3cm}{nom.}    |
| soṇḍāya vā       | \fillin{5cm}{by the trunk}          | \fillin{3cm}{inst.}   |
| dīghahatthena vā | \fillin{5cm}{or by the long hand}   | \fillin{3cm}{inst.}   |
| attano           | \fillin{5cm}{her own}               | \fillin{3cm}{gen.}    |
| hatthipotakassa  | \fillin{5cm}{to the baby-elephant}  | \fillin{3cm}{dat.}    |
| tiṇaṁ           | \fillin{5cm}{grass}                 | \fillin{3cm}{acc.}    |
| datvā            | \fillin{5cm}{having given}          | \fillin{3cm}{ger.}    |
| tato             | \fillin{5cm}{then}                  | \fillin{3cm}{ind.}    |
| vīriyārambhāya   | \fillin{5cm}{for making effort}     | \fillin{3cm}{dat.}    |
| soṇḍato          | \fillin{5cm}{from the trunk}        | \fillin{3cm}{abl.}    |
| mahāsaddaṁ      | \fillin{5cm}{a loud noise}          | \fillin{3cm}{acc.}    |
| pahiṇi           | \fillin{5cm}{sent (→ pahiṇāti)}     | \fillin{3cm}{aor.}    |
| imassa           | \fillin{5cm}{pron. of this (→ ima)} | \fillin{3cm}{gen.sg.} |
| hatthipotakassa  | \fillin{5cm}{of the baby elephant}  | \fillin{3cm}{gen.}    |
| tiṇena           | \fillin{5cm}{with grass}            | \fillin{3cm}{inst.}   |
| kucchi           | \fillin{5cm}{belly, stomach}        | \fillin{3cm}{nom.}    |
| mahanto          | \fillin{5cm}{adj. great, large}     | \fillin{3cm}{nom.}    |
| ahosi            | \fillin{5cm}{was, became (→ hoti)}  | \fillin{3cm}{aor.}    |

#+latex: \normalArrayStretch

\clearpage

*** Notes                                                          :noexport:

soṇḍa origin:

The Hungarian dictionary says "szonda" is from the French "sonde" (tool for
water-depth measurement or medical probe), and the French word is
Proto-Indo-European

https://en.wiktionary.org/wiki/sonde#French
* More                                                             :noexport:
** Akuppā me vimutti / kuppapaṭicca santi
*** akuppā me vimutti

#+begin_quote
Ñāṇañca pana me dassanaṁ udapādi, akuppā me vimutti ayam-antimā jāti, natthi dāni punabbhavo'ti.

Idam-avoca bhagavā. Attamanā pañcavaggiyā bhikkhū bhagavato bhāsitaṁ abhinanduṁ.

Imasmiñca pana veyyākaraṇasmiṁ bhaññamāne āyasmato koṇḍaññassa virajaṁ vītamalaṁ dhammacakkhuṁ udapādi:

yaṁ kiñci samudaya-dhammaṁ sabban-taṁ nirodha-dhamman'ti.
#+end_quote

Dhammacakkappavattana

*** akuppā cetovimutti

The term *akuppā cetovimutti*, "unshakeable deliverance of the mind", expresses
the same idea. Sometimes the Buddha refers to Nibbāna as *akuppā
cetovimutti*.[^fn285] All other such deliverances are shakeable, or irritable.

MN 29 Mahāsāropamasutta [[http://localhost:4848/suttas/mn29/pli/ms?quote=akupp%25C4%2581%2520cetovimutti&window_type=Sutta+Study][SSP]]

*** acalaṁ sukhaṁ

Sermon 8

# Then, in which sense is Nibbāna called *dhuva*? In the sense that the experience
# of Nibbāna is irreversible. That is why it is referred to as *acalaṁ
# sukhaṁ*, "unshakeable bliss".

Ud 8.10 [[http://localhost:4848/suttas/ud8.10/pli/ms?quote=acala%25E1%25B9%2581%2520sukhan&window_type=Sutta+Study][SSP]]
Thag 3.16 Vimala Thera [[http://localhost:4848/suttas/thag3.16/pli/ms?quote=patthento%2520acala%25E1%25B9%2581%2520sukha%25E1%25B9%2581&window_type=Sutta+Study][SSP]]

#+begin_quote
Atha kho bhagavā etamatthaṁ viditvā tāyaṁ velāyaṁ imaṁ udānaṁ udānesi:

“Ayoghanahatasseva,
jalato jātavedaso;
Anupubbūpasantassa,
yathā na ñāyate gati.

Evaṁ sammāvimuttānaṁ,
kāmabandhoghatārinaṁ;
Paññāpetuṁ gati natthi,
pattānaṁ acalaṁ sukhan”ti.
#+end_quote

*** kuppapaṭicca santi

# As the expression *kuppapaṭicca santi*, "peace dependent on
# irritability", implies, they are irritable and shakeable.

Snp 4.3 Duṭṭhaṭṭhakasutta ([[https://www.digitalpalireader.online/_dprhtml/index.html?loc=k.4.0.0.3.0.2.m][DPR]], [[http://localhost:4848/suttas/snp4.3/pli/ms?quote=Ta%25E1%25B9%2581%2520nissito%2520kuppapa%25E1%25B9%25ADiccasanti%25E1%25B9%2581&window_type=Sutta+Study][SSP]])

#+begin_quote
Sakañhi diṭṭhiṁ kathamaccayeyya,
Chandānunīto ruciyā niviṭṭho;
...

Santo ca bhikkhu abhinibbutatto,
Itihanti sīlesu akatthamāno;
Tamariyadhammaṁ kusalā vadanti,
Yassussadā natthi kuhiñci loke.

Pakappitā saṅkhatā yassa dhammā,
Purakkhatā santi avīvadātā;
Yadattani passati ānisaṁsaṁ,
Taṁ nissito kuppapaṭiccasantiṁ.

Diṭṭhīnivesā na hi svātivattā,
Dhammesu niccheyya samuggahītaṁ;
Tasmā naro tesu nivesanesu,
Nirassatī ādiyatī ca dhammaṁ.

Dhonassa hi natthi kuhiñci loke,
Pakappitā diṭṭhi bhavābhavesu;
Māyañca mānañca pahāya dhono,
Sa kena gaccheyya anūpayo so.
#+end_quote

*** kiṁ kuppissati

Sermon 14

> *amiyyamāno kiṁ kuppissati, akuppamāno kissa pihessati,*
>
> not dying, how shall he be shaken, and being unshaken, what shall he long
> for?

> *Yatthaṭṭhitaṁ maññussavā nappavattanti, maññussave kho pana nappavattamāne
> muni santo ti vuccatīti, iti yaṁ taṁ vuttaṁ, idam etaṁ paṭicca
> vuttaṁ*.[^fn479]

[^fn479]: M III 246, *Dhātuvibhaṅgasutta*

** Chanting: Mettāya, bhikkhave

\casesLegendHeaderBGHere

#+begin_quote
Mettāya, bhikkhave, cetovimuttiyā āsevitāya bhāvitāya bahulīkatāya yānīkatāya

vatthukatāya anuṭṭhitāya paricitāya susamāraddhāya ekādasānisaṁsā pāṭikaṅkhā.

Katame ekādasa? Sukhaṁ supati, sukhaṁ paṭibujjhati, na pāpakaṁ supinaṁ passati,

manussānaṁ piyo hoti, amanussānaṁ piyo hoti, devatā rakkhanti,

nāssa aggi vā visaṁ vā satthaṁ vā kamati,

tuvaṭaṁ cittaṁ samādhiyati, mukhavaṇṇo vippasīdati,

asammūḷho kālaṁ karoti, uttari appaṭivijjhanto brahmalokūpago hoti.
#+end_quote

\vspace*{2\baselineskip}

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo}
| āsevita (pp.)          | practised persistently; pp of āsevati                   |
| pāṭikaṅkha (ptp. +dat) | to be expected (for); certain (for); can be anticipated |
|                        | ptp of paṭikaṅkhati                                     |

*** Links

[[http://localhost:4848/suttas/an11.15/pli/ms?window_type=Sutta+Study][AN 11.15 (SSP)]]

** Chanting: Āyudo balado dhīro

\casesLegendHeaderBGHere

#+begin_quote
Āyudo balado dhīro, / vaṇṇado paṭibhānado;

Sukhassa dātā medhāvī, / sukhaṁ so adhigacchati.

Āyuṁ datvā balaṁ vaṇṇaṁ, / sukhañca paṭibhānado;

Dīghāyu yasavā hoti, / yattha yatthūpapajjatī”ti.
#+end_quote

\vspace*{2\baselineskip}

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo}
| āyuda (adj.)    | giving life [āyu + da]                                      |
| dhīra (m.)      | wise man; intelligent person [√dhī + ra]                    |
| paṭibhāna (nt.) | wit; intelligence; quick response                           |
|                 | lit. speaking back [pati + √bhaṇ + *a]                      |
| medhāvī (m.)    | intelligent man; who has good judgment; lit. who has wisdom |
|                 | [√medh + ā + vī]                                            |
| yasavant (adj.) | famous; renowned                                            |
| yattha (ind.)   | wherever; where                                             |
| upapajjati      | is reborn (in); re-arises (in); lit. goes towards           |

\clearpage

*** Links                                                          :noexport:
** Jaṭā Sutta (SN 7.6)                                             :noexport:

Sāvatthinidānaṁ. Atha kho jaṭābhāradvājo brāhmaṇo yena bhagavā tenupasaṅkami;

upasaṅkamitvā bhagavatā saddhiṁ sammodi.

Sammodanīyaṁ kathaṁ sāraṇīyaṁ vītisāretvā ekamantaṁ nisīdi.

Ekamantaṁ nisinno kho jaṭābhāradvājo brāhmaṇo bhagavantaṁ gāthāya ajjhabhāsi:

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo}
| sammodati (+instr)               | greets; exchanges pleasantries (with)        |
| bhagavatā                        | instr.sg. of bhagavant                       |
| sammodanīya (ptp.)               | lit. to be enjoyed; ptp. of sammodati        |
| sāraṇīya (ptp.)                  | polite; lit. to be desired; ptp of sārajjati |
| vītisāreti                       | conducts, concludes (a conversation)         |
| gāthā (f.)                       | verse; poem; stanza; lit. song               |
| ajjhabhāsi (aor. +acc & +instr)  | addressed; spoke (to someone with)           |

“Antojaṭā bahijaṭā, / Jaṭāya jaṭitā pajā;

Taṁ taṁ gotama pucchāmi, / Ko imaṁ vijaṭaye jaṭan”ti.

“Sīle patiṭṭhāya naro sapañño, / Cittaṁ paññañca bhāvayaṁ;

Ātāpī nipako bhikkhu, / So imaṁ vijaṭaye jaṭaṁ.

Yesaṁ rāgo ca doso ca, / Avijjā ca virājitā;

Khīṇāsavā arahanto, / Tesaṁ vijaṭitā jaṭā.

Yattha nāmañca rūpañca, / Asesaṁ uparujjhati;

Paṭighaṁ rūpasaññā ca, / Etthesā chijjate jaṭā”ti.

Evaṁ vutte, jaṭābhāradvājo bhagavantaṁ etadavoca:

“abhikkantaṁ, bho gotama …pe… aññataro ca panāyasmā bhāradvājo arahataṁ ahosī”ti.

\bigskip

([[http://localhost:4848/suttas/s0301a.att/pli/cst4?quote=ja%25E1%25B9%25AD%25C4%2581pa%25C3%25B1hassa%2520pana%2520pucchitatt%25C4%2581&window_type=Sutta+Study][Aṭṭhakathā]]) jaṭāsuttavaṇṇanā:

\textbf{jaṭābhāradvājo}ti bhāradvājovesa, jaṭāpañhassa pana pucchitattā saṅgītikārehi evaṁ vutto.

*** Links                                                          :noexport:

[[id:5f92c53b-fbf1-4505-a191-a507b8fb14c2][Jaṭā Sutta (SN 7.6)]]

[[http://localhost:4848/suttas/sn7.6/pli/ms?window_type=Sutta+Study][SN 7.6 Jaṭāsutta (SSP)]], the tangle within and without

Translation by Bh Bodhi: [[http://localhost:4848/suttas/sn1.23/en/bodhi?window_type=Sutta+Study][SN 1.23 (SSP)]]

DPPN:

DPPN: Bhāradvāja. The name of a brahmin clan; about twenty individuals belonging to
this clan are mentioned in the Pitakas.

Jaṭā bhāradvāja: A brahmin of the Bhāradvājagotta.

The Commentary (SA.i.179) says that he was given this name by the Recensionists
because he asked a question about jatā (tangle).

([[http://localhost:4848/suttas/s0301a.att/pli/cst4?quote=ja%25E1%25B9%25AD%25C4%2581pa%25C3%25B1hassa%2520pana%2520pucchitatt%25C4%2581&window_type=Sutta+Study][Aṭṭhakathā]]) jaṭāsuttavaṇṇanā:

__jaṭābhāradvājo__ti bhāradvājovesa, jaṭāpañhassa pana pucchitattā saṅgītikārehi evaṁ vutto.

([[http://localhost:4848/suttas/s0301t.tik/pli/cst4?quote=antoja%25E1%25B9%25AD%25C4%2581%2520bahija%25E1%25B9%25AD%25C4%2581&window_type=Sutta+Study][Ṭīkā]]) jaṭāsuttavaṇṇanā:

__jaṭāpañhassā__ti ‘‘antojaṭā bahijaṭā’’ti evaṁ jaṭāpariyāyassa pañhassa.

**** Meter

2.3 Siloka (Śloka) a.k.a. Vatta (Vaktra) & Anuṭṭhubha (Anuṣṭubh)
https://ancient-buddhist-texts.net/Textual-Studies/Outline/2-Outline-03.htm

: A Siloka verse normally consists of 4 lines (sometimes 6, rarely 5) with 8
: syllables to the line, organised in dissimilar pairs which are repeated to make
: up a verse (note that owing to resolution sometimes a Siloka line may contain 9
: syllables).

What is the meter of Jaṭā Sutta (SN 7.6)?

“Antojaṭā bahijaṭā,
jaṭāya jaṭitā pajā;
Taṁ taṁ gotama pucchāmi,
ko imaṁ vijaṭaye jaṭan”ti.

------

NORBU: The verse you've quoted from the Jaṭā Sutta (SN 7.6) is in a meter known
as Śloka (also spelled Sloka) in Sanskrit, or Siloka in Pali. This is one of the
most common meters used in Sanskrit and Pali poetry, including many Buddhist
texts.

The Śloka meter consists of four padas (lines) of eight syllables each, making a
total of 32 syllables per verse. The basic structure is as follows:

1st line: 8 syllables
2nd line: 8 syllables
3rd line: 8 syllables
4th line: 8 syllables

In the verse you've provided:

"Antojaṭā bahijaṭā, (8 syllables)
jaṭāya jaṭitā pajā; (8 syllables)
Taṁ taṁ gotama pucchāmi, (8 syllables)
ko imaṁ vijaṭaye jaṭan"ti. (8 syllables)

Each line indeed contains 8 syllables, conforming to the Śloka meter. This meter
is widely used in Buddhist literature, including the Dhammapada and many suttas,
due to its simplicity and ease of memorization, which was crucial in the oral
transmission of these teachings.

-------

Question: What is the history of the Śloka / Siloka meter?

NORBU: The Śloka meter has a long and significant history in Indian literature,
including Buddhist texts. Here's an overview of its development and importance:

1. Vedic Origins: The Śloka meter evolved from the Vedic Anuṣṭubh meter, which
   was used in the Rigveda. The Anuṣṭubh consisted of four padas of eight
   syllables each, much like the Śloka.

2. Epic Period: The Śloka gained prominence during the composition of the great
   Indian epics, the Ramayana and the Mahabharata (circa 5th-4th century BCE).
   It became the primary meter for narrative poetry.

3. Classical Sanskrit: In classical Sanskrit literature, the Śloka became highly
   refined. Poets like Kalidasa (c. 4th-5th century CE) used it extensively in
   their works.

4. Buddhist Adoption: As Buddhism emerged and spread, it adopted the Śloka meter
   for its own texts. Many suttas in the Pali Canon, including parts of the
   Sutta Nipata and the entire Dhammapada, use this meter.

5. Flexibility and Popularity: The Śloka's popularity stemmed from its
   flexibility. It allowed for variations in the arrangement of long and short
   syllables, making it adaptable to different linguistic contexts.

6. Mnemonic Device: In oral traditions, the Śloka's rhythmic structure made it
   an excellent mnemonic device for preserving and transmitting teachings.

7. Pan-Indian Usage: The Śloka transcended linguistic and religious boundaries,
   being used in Sanskrit, Pali, and various Prakrits, and in Hindu, Buddhist,
   and Jain texts.

8. Continued Use: Even in modern times, the Śloka remains a popular meter in
   Indian languages for religious and didactic poetry.

The Śloka's enduring popularity in Buddhist literature demonstrates its
effectiveness in conveying complex philosophical and spiritual concepts in a
memorable form. Its use in texts like the Jaṭā Sutta exemplifies how Buddhist
teachers adapted existing cultural forms to spread the Dhamma.
** Chanting

uppannāya taṇhā꜔꜒ya ponobhavikāya na vasa꜔꜒ṁ gacchissa꜔꜒nti

Ye ca kho tvaṁ, gotami, dhamme jāneyyāsi:
‘ime dhammā virāgāya saṁvattanti, no sarāgāya;

** Vinaya

tinaṁ vā...
