# -*- flyspell-lazy-local: nil; mode: Org; eval: (progn (flycheck-mode 0) (flyspell-mode 0) (toggle-truncate-lines 1)) -*-
#+LATEX_CLASS: memoir
#+LATEX_HEADER: \input{./pali-lessons-preamble.tex}
#+LATEX_HEADER: \maxtocdepth{section}
#+LANGUAGE: en_GB
#+OPTIONS: toc:nil tasks:nil H:4 author:nil ':t ^:{}
#+TITLE: Pāli Readings (Next)
#+AUTHOR: The Bhikkhu Saṅgha

#+begin_export latex
\makeatletter

\newlength{\colOne}\setlength{\colOne}{0.35\linewidth}
\newlength{\colTwo}\setlength{\colTwo}{0.6\linewidth}

\renewenvironment{quote}%
{\list{}{%
    \doubleLineSize
    \listparindent 0pt
    \itemindent    0pt
    \leftmargin    3em
    \rightmargin   3em
    \parsep        0pt
    \topsep        8pt
    \partopsep     0pt}%
\item[] \raggedright}%
{\endlist}

\renewcommand*\sentenceDiaSolution[2][0.4]{%
  \ifanswerkey%
    \hspace*{-\spinemargin}%
    \begin{minipage}{\paperwidth}%
      \centering%
      \includegraphics[scale=#1]{#2}%
    \end{minipage}%
  \fi%
}

\makeatother

\mainmatter
#+end_export

* Tasks                                                            :noexport:
* Links                                                            :noexport:

[[https://www.tldraw.com/r/XXFsr0LAbq5hnpIPk68oZ?d=v-271.-85.1879.981.-MoEVvzvSGwo5y3S6Xo4B][tldraw 2024 (class) edit]]

[[https://www.tldraw.com/ro/PhYEAoE4a35dCVhtF-hEB?d=v-205.-141.1879.1015.page][tldraw 2024 (class) view]]

[[https://www.tldraw.com/r/NBh0Ae8CWE1As8DiFaGI9?d=v-190.-177.1879.981.page][tldraw 2024 (solved)]]

* Notes                                                            :noexport:

pali execrise: sentences from satipatthana? dasadhamma? anumodana?

"Jetavane hatthinī soṇḍāya vā dīghahatthena vā attano hatthipotakassa tiṇaṃ datvā,
tato vīriyārambhāya soṇḍato mahāsaddaṃ pahiṇi."

Continue the above Pali sentence with another sentence like "Imassa hatthipotakassa ... hoti."

-----

Translate: The belly of this baby elephant grew large with grass.

"Imassa hatthipotakassa tiṇena kucchi mahanto ahosi."

In this Pali sentence:

- "Imassa" means "of this"
- "Hatthipotakassa" means "of the baby elephant"
- "Tiṇena" means "with grass" (tiṇa means "grass", and -ena is the instrumental case ending)
- "Kucchi" means "belly" or "stomach"
- "Mahanto" means "large" or "big"
- "Ahosi" is the past tense of "hoti" meaning "became" or "grew"

1. Imassa:
- Genitive singular form of "ayaṃ" (this)
- Means "of this"

2. Hatthipotakassa:
- Genitive singular form of "hatthipotaka" (baby elephant)
- "Hatthi" means elephant, "potaka" means young animal or baby
- Means "of the baby elephant"

3. Tiṇena:
- Instrumental singular form of "tiṇa" (grass)
- Means "with grass" or "by means of grass"

4. Kucchi:
- Nominative singular form
- Means "belly" or "stomach"

5. Mahanto:
- Nominative singular masculine form of "mahant" (great, large)
- Means "large" or "big"

6. Ahosi:
- Third person singular past tense of the verb "hoti" (to be, to become)
- Means "became" or "was"

-----

Panassa hatthipotakassa domanassaṃ uppajjati, so kadaliphalaṃ khādituṃ icchati" translates to:

"This baby elephant became unhappy, he wants to eat banana."

In this Pali translation:
- "Panassa" means "for this"
- "Hatthipotakassa" means "for the baby elephant"
- "Domanassaṃ" means "unhappiness" or "displeasure"
- "Uppajjati" means "arises" or "is born" (which we can interpret as "became" in this context)
- "So" means "he"
- "Kadaliphalaṃ" means "banana" (literally "fruit of the plantain")
- "Khādituṃ" means "to eat"
- "Icchati" means "wants" or "desires"

-----

The added part "Panassa hatthipotakassa tiṇaṃ khādituṃ na ruccati" can be translated as:

"However, the baby elephant does not like to eat grass."

In this continuation:
- "Pana" means "however" or "but"
- "Assa" is a genitive pronoun meaning "his" or "its"
- "Hatthipotakassa" is "of the baby elephant" (genitive)
- "Tiṇaṃ khādituṃ" means "to eat grass"
- "Na ruccati" means "does not like" or "is not pleased"

-----

"Imassa hatthipotakassa sikkhāpanatthāya mātā punappunaṃ tiṇaṃ adāsi."

The added part translates to:

"For the purpose of training this baby elephant, the mother repeatedly gave grass."

------

"Imassa hatthipotakassa bhojanaṃ datvā, mātā taṃ uyyojesi, 'Idāni tvaṃ sayameva
tiṇaṃ khādituṃ sikkhāhī'ti."

Which translates to:

"Having given food to this baby elephant, the mother encouraged it, saying, 'Now
you must learn to eat grass by yourself.'"

* More                                                             :noexport:
** Chanting: Mettāya, bhikkhave

\casesLegendHeaderBGHere

#+begin_quote
Mettāya, bhikkhave, cetovimuttiyā āsevitāya bhāvitāya bahulīkatāya yānīkatāya

vatthukatāya anuṭṭhitāya paricitāya susamāraddhāya ekādasānisaṁsā pāṭikaṅkhā.

Katame ekādasa? Sukhaṁ supati, sukhaṁ paṭibujjhati, na pāpakaṁ supinaṁ passati,

manussānaṁ piyo hoti, amanussānaṁ piyo hoti, devatā rakkhanti,

nāssa aggi vā visaṁ vā satthaṁ vā kamati,

tuvaṭaṁ cittaṁ samādhiyati, mukhavaṇṇo vippasīdati,

asammūḷho kālaṁ karoti, uttari appaṭivijjhanto brahmalokūpago hoti.
#+end_quote

\vspace*{2\baselineskip}

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo}
| āsevita (pp.)          | practised persistently; pp of āsevati                   |
| pāṭikaṅkha (ptp. +dat) | to be expected (for); certain (for); can be anticipated |
|                        | ptp of paṭikaṅkhati                                     |

*** Links

[[http://localhost:4848/suttas/an11.15/pli/ms?window_type=Sutta+Study][AN 11.15 (SSP)]]

** Chanting: Āyudo balado dhīro

\casesLegendHeaderBGHere

#+begin_quote
Āyudo balado dhīro, / vaṇṇado paṭibhānado;

Sukhassa dātā medhāvī, / sukhaṁ so adhigacchati.

Āyuṁ datvā balaṁ vaṇṇaṁ, / sukhañca paṭibhānado;

Dīghāyu yasavā hoti, / yattha yatthūpapajjatī”ti.
#+end_quote

\vspace*{2\baselineskip}

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo}
| āyuda (adj.)    | giving life [āyu + da]                                      |
| dhīra (m.)      | wise man; intelligent person [√dhī + ra]                    |
| paṭibhāna (nt.) | wit; intelligence; quick response                           |
|                 | lit. speaking back [pati + √bhaṇ + *a]                      |
| medhāvī (m.)    | intelligent man; who has good judgment; lit. who has wisdom |
|                 | [√medh + ā + vī]                                            |
| yasavant (adj.) | famous; renowned                                            |
| yattha (ind.)   | wherever; where                                             |
| upapajjati      | is reborn (in); re-arises (in); lit. goes towards           |

\clearpage

*** Links                                                          :noexport:
** Akusala / Kusala (MN 9)                                         :noexport:

definition of akusala (rāga, dosa, moha (avijjā))

and kusala (arāga...)

** Jaṭā Sutta (SN 7.6)                                             :noexport:

Sāvatthinidānaṁ. Atha kho jaṭābhāradvājo brāhmaṇo yena bhagavā tenupasaṅkami;

upasaṅkamitvā bhagavatā saddhiṁ sammodi.

Sammodanīyaṁ kathaṁ sāraṇīyaṁ vītisāretvā ekamantaṁ nisīdi.

Ekamantaṁ nisinno kho jaṭābhāradvājo brāhmaṇo bhagavantaṁ gāthāya ajjhabhāsi:

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo}
| sammodati (+instr)               | greets; exchanges pleasantries (with)        |
| bhagavatā                        | instr.sg. of bhagavant                       |
| sammodanīya (ptp.)               | lit. to be enjoyed; ptp. of sammodati        |
| sāraṇīya (ptp.)                  | polite; lit. to be desired; ptp of sārajjati |
| vītisāreti                       | conducts, concludes (a conversation)         |
| gāthā (f.)                       | verse; poem; stanza; lit. song               |
| ajjhabhāsi (aor. +acc & +instr)  | addressed; spoke (to someone with)           |

“Antojaṭā bahijaṭā, / Jaṭāya jaṭitā pajā;

Taṁ taṁ gotama pucchāmi, / Ko imaṁ vijaṭaye jaṭan”ti.

“Sīle patiṭṭhāya naro sapañño, / Cittaṁ paññañca bhāvayaṁ;

Ātāpī nipako bhikkhu, / So imaṁ vijaṭaye jaṭaṁ.

Yesaṁ rāgo ca doso ca, / Avijjā ca virājitā;

Khīṇāsavā arahanto, / Tesaṁ vijaṭitā jaṭā.

Yattha nāmañca rūpañca, / Asesaṁ uparujjhati;

Paṭighaṁ rūpasaññā ca, / Etthesā chijjate jaṭā”ti.

Evaṁ vutte, jaṭābhāradvājo bhagavantaṁ etadavoca:

“abhikkantaṁ, bho gotama …pe… aññataro ca panāyasmā bhāradvājo arahataṁ ahosī”ti.

\bigskip

([[http://localhost:4848/suttas/s0301a.att/pli/cst4?quote=ja%25E1%25B9%25AD%25C4%2581pa%25C3%25B1hassa%2520pana%2520pucchitatt%25C4%2581&window_type=Sutta+Study][Aṭṭhakathā]]) jaṭāsuttavaṇṇanā:

\textbf{jaṭābhāradvājo}ti bhāradvājovesa, jaṭāpañhassa pana pucchitattā saṅgītikārehi evaṃ vutto.

*** Links                                                          :noexport:

[[id:5f92c53b-fbf1-4505-a191-a507b8fb14c2][Jaṭā Sutta (SN 7.6)]]

[[http://localhost:4848/suttas/sn7.6/pli/ms?window_type=Sutta+Study][SN 7.6 Jaṭāsutta (SSP)]], the tangle within and without

Translation by Bh Bodhi: [[http://localhost:4848/suttas/sn1.23/en/bodhi?window_type=Sutta+Study][SN 1.23 (SSP)]]

DPPN:

DPPN: Bhāradvāja. The name of a brahmin clan; about twenty individuals belonging to
this clan are mentioned in the Pitakas.

Jaṭā bhāradvāja: A brahmin of the Bhāradvājagotta.

The Commentary (SA.i.179) says that he was given this name by the Recensionists
because he asked a question about jatā (tangle).

([[http://localhost:4848/suttas/s0301a.att/pli/cst4?quote=ja%25E1%25B9%25AD%25C4%2581pa%25C3%25B1hassa%2520pana%2520pucchitatt%25C4%2581&window_type=Sutta+Study][Aṭṭhakathā]]) jaṭāsuttavaṇṇanā:

__jaṭābhāradvājo__ti bhāradvājovesa, jaṭāpañhassa pana pucchitattā saṅgītikārehi evaṃ vutto.

([[http://localhost:4848/suttas/s0301t.tik/pli/cst4?quote=antoja%25E1%25B9%25AD%25C4%2581%2520bahija%25E1%25B9%25AD%25C4%2581&window_type=Sutta+Study][Ṭīkā]]) jaṭāsuttavaṇṇanā:

__jaṭāpañhassā__ti ‘‘antojaṭā bahijaṭā’’ti evaṁ jaṭāpariyāyassa pañhassa.

**** Meter

2.3 Siloka (Śloka) a.k.a. Vatta (Vaktra) & Anuṭṭhubha (Anuṣṭubh)
https://ancient-buddhist-texts.net/Textual-Studies/Outline/2-Outline-03.htm

: A Siloka verse normally consists of 4 lines (sometimes 6, rarely 5) with 8
: syllables to the line, organised in dissimilar pairs which are repeated to make
: up a verse (note that owing to resolution sometimes a Siloka line may contain 9
: syllables).

What is the meter of Jaṭā Sutta (SN 7.6)?

“Antojaṭā bahijaṭā,
jaṭāya jaṭitā pajā;
Taṁ taṁ gotama pucchāmi,
ko imaṁ vijaṭaye jaṭan”ti.

------

NORBU: The verse you've quoted from the Jaṭā Sutta (SN 7.6) is in a meter known
as Śloka (also spelled Sloka) in Sanskrit, or Siloka in Pali. This is one of the
most common meters used in Sanskrit and Pali poetry, including many Buddhist
texts.

The Śloka meter consists of four padas (lines) of eight syllables each, making a
total of 32 syllables per verse. The basic structure is as follows:

1st line: 8 syllables
2nd line: 8 syllables
3rd line: 8 syllables
4th line: 8 syllables

In the verse you've provided:

"Antojaṭā bahijaṭā, (8 syllables)
jaṭāya jaṭitā pajā; (8 syllables)
Taṁ taṁ gotama pucchāmi, (8 syllables)
ko imaṁ vijaṭaye jaṭan"ti. (8 syllables)

Each line indeed contains 8 syllables, conforming to the Śloka meter. This meter
is widely used in Buddhist literature, including the Dhammapada and many suttas,
due to its simplicity and ease of memorization, which was crucial in the oral
transmission of these teachings.

-------

Question: What is the history of the Śloka / Siloka meter?

NORBU: The Śloka meter has a long and significant history in Indian literature,
including Buddhist texts. Here's an overview of its development and importance:

1. Vedic Origins: The Śloka meter evolved from the Vedic Anuṣṭubh meter, which
   was used in the Rigveda. The Anuṣṭubh consisted of four padas of eight
   syllables each, much like the Śloka.

2. Epic Period: The Śloka gained prominence during the composition of the great
   Indian epics, the Ramayana and the Mahabharata (circa 5th-4th century BCE).
   It became the primary meter for narrative poetry.

3. Classical Sanskrit: In classical Sanskrit literature, the Śloka became highly
   refined. Poets like Kalidasa (c. 4th-5th century CE) used it extensively in
   their works.

4. Buddhist Adoption: As Buddhism emerged and spread, it adopted the Śloka meter
   for its own texts. Many suttas in the Pali Canon, including parts of the
   Sutta Nipata and the entire Dhammapada, use this meter.

5. Flexibility and Popularity: The Śloka's popularity stemmed from its
   flexibility. It allowed for variations in the arrangement of long and short
   syllables, making it adaptable to different linguistic contexts.

6. Mnemonic Device: In oral traditions, the Śloka's rhythmic structure made it
   an excellent mnemonic device for preserving and transmitting teachings.

7. Pan-Indian Usage: The Śloka transcended linguistic and religious boundaries,
   being used in Sanskrit, Pali, and various Prakrits, and in Hindu, Buddhist,
   and Jain texts.

8. Continued Use: Even in modern times, the Śloka remains a popular meter in
   Indian languages for religious and didactic poetry.

The Śloka's enduring popularity in Buddhist literature demonstrates its
effectiveness in conveying complex philosophical and spiritual concepts in a
memorable form. Its use in texts like the Jaṭā Sutta exemplifies how Buddhist
teachers adapted existing cultural forms to spread the Dhamma.
** Chanting

uppannāya taṇhā꜔꜒ya ponobhavikāya na vasa꜔꜒ṁ gacchissa꜔꜒nti

Ye ca kho tvaṁ, gotami, dhamme jāneyyāsi:
‘ime dhammā virāgāya saṁvattanti, no sarāgāya;

** Vinaya

tinaṁ vā...

* Name-and-Form                                                    :noexport:
** Links                                                           :noexport:

[[https://www.tldraw.com/r/XXFsr0LAbq5hnpIPk68oZ?d=v-271.-85.1879.981.-MoEVvzvSGwo5y3S6Xo4B][tldraw: name-and-form (class)]]

[[https://www.tldraw.com/r/NBh0Ae8CWE1As8DiFaGI9?d=v-190.-177.1879.981.page][tldraw solved]]

** Right View and Name-and-Form (MN 9)

#+begin_quote
Āyasmā sāriputto etadavoca: “‘Sammādiṭṭhi sammādiṭṭhī’ti, āvuso, vuccati.

Kittāvatā nu kho, āvuso, ariyasāvako sammādiṭṭhi hoti,

ujugatāssa diṭṭhi, dhamme aveccappasādena samannāgato,

āgato imaṁ saddhamman”ti?
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo}
| avoca (aor. +acc & +acc)  | said (something to somebody); aor. of vacati     |
| vuccati (pr.)             | is said to be; is called; pass. of vacati        |
| diṭṭhi (f.)               | view; belief                                     |
| kittāvatā                 | in what way? [ka + tāva + tā]                    |
| ujugata (adj.)            | correct; lit. gone straight [uju + gata]         |
| assa (pron.)              | for him; dat. of ima                             |
| aveccappasāda (m.)        | perfect clarity [avecca + pasāda]                |
| avecca (ind.)             | perfectly; absolutely; lit. going into           |
| samannāgata (pp. +instr.) | possessing; endowed (with); having;              |
|                           | lit. going together [saṁ + anu + ā + √gam + ta] |
| āgata (pp.)               | become; entered (into a state); pp. of āgacchati |

#+latex: \sentenceDiaSolution{./images/mn9-ayasma-sariputto-etadavoca.png}

\ifanswerkey
\clearpage
\casesLegendHeaderBGHere
\fi

#+begin_quote
Katamaṁ panāvuso, nāmarūpaṁ, katamo nāmarūpasamudayo,

katamo nāmarūpanirodho, katamā nāmarūpanirodhagāminī paṭipadā?

Vedanā, saññā, cetanā, phasso, manasikāro

— idaṁ vuccatāvuso, nāmaṁ;

cattāri ca mahābhūtāni, catunnañca mahābhūtānaṁ upādāyarūpaṁ

— idaṁ vuccatāvuso, rūpaṁ.
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo}
| vuccatāvuso       | is called, friend; sandhi. vuccati + āvuso        |
| upādāyarūpa (nt.) | derived materiality (of) [upādāya + rūpa]         |
| upādāya (ind.)    | derived (from); dependent (on); ger. of upādiyati |
|                   | lit. taking near                                  |

#+latex: \sentenceDiaSolution{./images/mn9-katamam-panavuso-namarupam.png}

\clearpage

#+begin_quote
Iti idañca nāmaṁ idañca rūpaṁ — idaṁ vuccatāvuso, nāmarūpaṁ.

Viññāṇasamudayā nāmarūpasamudayo, viññāṇanirodhā nāmarūpanirodho,

ayameva ariyo aṭṭhaṅgiko maggo nāmarūpanirodhagāminī paṭipadā,

seyyathidaṁ — sammādiṭṭhi …pe… sammāsamādhi.
#+end_quote

#+latex: \sentenceDiaSolution{./images/mn9-iti-idanca-namam.png}

\ifanswerkey\else
\casesLegendHeaderBGHere
\fi

#+begin_quote
Yato kho, āvuso, ariyasāvako evaṁ nāmarūpaṁ pajānāti,

evaṁ nāmarūpasamudayaṁ pajānāti, evaṁ nāmarūpanirodhaṁ pajānāti,

evaṁ nāmarūpanirodhagāminiṁ paṭipadaṁ pajānāti,
#+end_quote

#+latex: \sentenceDiaSolution{./images/mn9-yato-kho-avuso.png}

\ifanswerkey\clearpage\fi

#+begin_quote
so sabbaso rāgānusayaṁ pahāya,

paṭighānusayaṁ paṭivinodetvā,

‘asmī’ti diṭṭhimānānusayaṁ samūhanitvā,

avijjaṁ pahāya vijjaṁ uppādetvā,

diṭṭheva dhamme dukkhassantakaro hoti —
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo}
| pajahati        | gives up; abandons                                 |
| vinodeti        | dispels; drives out; caus of vi √nud               |
| samūhanati      | eradicates; kills off;                             |
|                 | lit. kills up together [saṁ + ud + √han + a + ti] |
| uppādeti        | generates; causes to arise; caus of uppajjati      |
| antakara (adj.) | makes an end (of) [anta + kara]                    |

#+latex: \sentenceDiaSolution{./images/mn9-so-sabbaso-raganusayam.png}

#+begin_quote
ettāvatāpi kho, āvuso, ariyasāvako sammādiṭṭhi hoti,

ujugatāssa diṭṭhi, dhamme aveccappasādena samannāgato,

āgato imaṁ saddhamman”ti.
#+end_quote

\clearpage

*** Links                                                          :noexport:

[[http://localhost:4848/suttas/mn9/pli/ms?quote=Katama%25E1%25B9%2581%2520pan%25C4%2581vuso%252C%2520n%25C4%2581mar%25C5%25ABpa%25E1%25B9%2581&window_type=Sutta+Study][MN 9 Sammādiṭṭhisutta (SSP)]], definition of name-and-form

list of ñānas, objectification, will experience the word
hypnotic suggestion

** Cases Exercise: The Elephant

\casesLegendHeaderBGHere

#+begin_quote
Jetavane hatthinī soṇḍāya vā dīghahatthena vā

attano hatthipotakassa tiṇaṃ datvā,

tato vīriyārambhāya soṇḍato mahāsaddaṃ pahiṇi.

Imassa hatthipotakassa tiṇena kucchi mahanto ahosi.
#+end_quote

# At Jetavana, the elephant gave grass to her own baby-elephant by the trunk (or by
# the long hand), then sent a loud noise from the trunk for making effort.
# The belly of this baby elephant grew large with grass.

#+latex: \vspace*{2\baselineskip}
#+latex: \renewcommand{\arraystretch}{1.6}

#+ATTR_LATEX: :environment longtable :align L{4cm} L{5cm} L{3cm}
| word             | meaning                             | case                  |
|------------------+-------------------------------------+-----------------------|
| Jetavane         | \fillin{5cm}{at Jetavana}           | \fillin{3cm}{loc.}    |
| hatthinī         | \fillin{5cm}{the female elephant}   | \fillin{3cm}{nom.}    |
| soṇḍāya vā       | \fillin{5cm}{by the trunk}          | \fillin{3cm}{inst.}   |
| dīghahatthena vā | \fillin{5cm}{or by the long hand}   | \fillin{3cm}{inst.}   |
| attano           | \fillin{5cm}{her own}               | \fillin{3cm}{gen.}    |
| hatthipotakassa  | \fillin{5cm}{to the baby-elephant}  | \fillin{3cm}{dat.}    |
| tiṇaṃ           | \fillin{5cm}{grass}                 | \fillin{3cm}{acc.}    |
| datvā            | \fillin{5cm}{having given}          | \fillin{3cm}{ger.}    |
| tato             | \fillin{5cm}{then}                  | \fillin{3cm}{ind.}    |
| vīriyārambhāya   | \fillin{5cm}{for making effort}     | \fillin{3cm}{dat.}    |
| soṇḍato          | \fillin{5cm}{from the trunk}        | \fillin{3cm}{abl.}    |
| mahāsaddaṃ      | \fillin{5cm}{a loud noise}          | \fillin{3cm}{acc.}    |
| pahiṇi           | \fillin{5cm}{sent (→ pahiṇāti)}     | \fillin{3cm}{aor.}    |
| imassa           | \fillin{5cm}{pron. of this (→ ima)} | \fillin{3cm}{gen.sg.} |
| hatthipotakassa  | \fillin{5cm}{of the baby elephant}  | \fillin{3cm}{gen.}    |
| tiṇena           | \fillin{5cm}{with grass}            | \fillin{3cm}{inst.}   |
| kucchi           | \fillin{5cm}{belly, stomach}        | \fillin{3cm}{nom.}    |
| mahanto          | \fillin{5cm}{adj. great, large}     | \fillin{3cm}{nom.}    |
| ahosi            | \fillin{5cm}{was, became (→ hoti)}  | \fillin{3cm}{aor.}    |

#+latex: \normalArrayStrech

\clearpage

*** Notes                                                          :noexport:

soṇḍa origin:

The Hungarian dictionary says "szonda" is from the French "sonde" (tool for
water-depth measurement or medical probe), and the French word is
Proto-Indo-European

https://en.wiktionary.org/wiki/sonde#French
* Pārājika 4                                                       :noexport:
** Exercise

#+begin_quote
Yasmā ca kho bhikkhave

\vin atthi ajātaṁ abhūtaṁ akataṁ asaṅkhataṁ

Tasmā jātassa bhūtassa katassa saṅkhatassa

\vin nissaraṇaṁ paññāyati.
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo}
| paññāyati | is clearly known; is evident; pass. of pajānāti |

#+begin_quote
Yan-dunnimittaṁ avamaṅgalañ-ca, yo cāmanāpo sakuṇassa saddo

Pāpaggaho dussupinaṁ akantaṁ, buddhānubhāvena vināsamentu
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo}
| gaha (m.)     | (1) grip; grabbing; from gaṇhāti  |
|               | (2) planet; lit. what is grasped  |
| ānubhāva (m.) | power; ability                    |
| vināsa (m.)   | destruction; ruin; from vinassati |
| eti (+acc)    | comes (to); goes (to); becomes     |

\vspace*{2\baselineskip}

** Pārājika 4

#+begin_quote
Yo pana bhikkhu anabhijānaṁ uttari-manussa-dhammaṁ

attūpanāyikaṁ alam-ariya-ñāṇa-dassanaṁ samudācareyya

“iti jānāmi, iti passāmī”ti.
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo}
| attūpanāyika (adj.) | referring to oneself [atta + upanāyika] |
| samudācarati        | asserts; announces                      |

\clearpage
\casesLegendHeaderBGHere

#+begin_quote
Tato aparena samayena

samanuggāhiyamāno vā asamanuggāhiyamāno vā

āpanno visuddhāpekkho evaṁ vadeyya,
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo}
| apara (adj.)                    | another; after                                       |
| samaya (m.)                     | time; occasion                                       |
| āpanna (pp. + acc.)             | fallen into; pp. of āpajjati                         |
| samanuggāhiyamāna (prp. +instr) | being closely questioned (by); lit. being dived into |
|                                 | [saṁ + anu + √gāh + īya + māna]                     |
| apekkha (adj.)                  | looking (for); desiring                              |

\vspace*{2\baselineskip}

#+begin_quote
“Ajānam-evaṁ āvuso avacaṁ 'jānāmi', apassaṁ 'passāmi'.

Tucchaṁ musā vilapi”nti.

Aññatra adhimānā: ayam-pi pārājiko hoti asaṁvāso.
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo}
| tucchaṁ (ind.) | emptily; vainly; without substance [tuccha + aṁ] |
| musā (ind.)     | falsely; untruthfully                             |
| vilapi          | talked nonsense; aor. of vilapati                 |

*** Links                                                          :noexport:

[[http://localhost:4848/suttas/pli-tv-bu-pm/pli/ms?quote=Yo%2520pana%2520bhikkhu%2520anabhij%25C4%2581na%25E1%25B9%2581&window_type=Sutta+Study][Pr 4 (SSP)]]

** Closing of Pr 4                                                 :noexport:

#+begin_quote
Uddiṭṭhā kho āyasmanto cattāro pārājikā dhammā,

yesaṁ bhikkhu aññataraṁ vā aññataraṁ vā āpajjitvā

na labhati bhikkhūhi saddhiṁ saṁvāsaṁ.

Yathā pure, tathā pacchā: pārājiko hoti asaṁvāso.
#+end_quote

#+begin_quote
Tatth'āyasmante pucchāmi: kacci'ttha parisuddhā?

Dutiyampi ... tatiyampi ...

Parisuddh'etth'āyasmanto, tasmā tuṇhī,

evam-etaṁ dhārayāmi.
#+end_quote

* Dhammapada 21-23                                                 :noexport:
** Chanting: Yaṅkiñci ratanaṁ loke

#+begin_quote
Yaṅkiñci ratanaṁ loke vijjati

vividhaṁ puthu ratanaṁ buddhasamaṁ natthi

tasmā sotthī bhavantu te
#+end_quote

\vspace*{2\baselineskip}

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo}
| vividha (adj.)   | various kinds of; assorted; multiple |
| puthu (ind.)     | far and wide; all over               |
| sama (adj.)      | level; even; balanced                |
| sama (nt.)       | similarity; equality                 |
| sotthi (f. +dat) | safety (for); well-being (for)       |
|                  | abstr, from atthi (+dat)             |

** Dhammapada: Sāmāvatīvatthu (Dhp 21-23)

#+begin_quote
Appamādo amatapadaṁ,

pamādo maccuno padaṁ;

Appamattā na mīyanti,

ye pamattā yathā matā.
#+end_quote

\vspace*{2\baselineskip}

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo}
| appamāda (m.) | lit. not heedless; [na + pamajjati] |
| maccu (m.)    | death                               |
| mīyati        | is killed; dies; pass of marati     |

\clearpage
\casesLegendHeaderBGHere

#+begin_quote
Evaṁ visesato ñatvā,

appamādamhi paṇḍitā;

Appamāde pamodanti,

ariyānaṁ gocare ratā.
#+end_quote

\vspace*{2\baselineskip}

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo}
| visesato (ind.)     | distinctly; clearly                          |
| pamodati (pr. +loc) | is delighted (with/about)                    |
| gocara (m.)         | food; grazing; pasture                       |
|                     | lit. (where the) cows walk [go + cara]       |
| rata (pp. +loc)     | pleased (with/about); enjoying; pp of ramati |

#+begin_quote
Te jhāyino sātatikā,

niccaṁ daḷhaparakkamā;

Phusanti dhīrā nibbānaṁ,

yogakkhemaṁ anuttaraṁ.
#+end_quote

\vspace*{2\baselineskip}

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo}
| jhāyī (adj.)          | meditating; contemplating; from jhāyati       |
| sātatika (adj.)       | persevering; consistent                       |
| daḷhaparakkama (adj.) | making continuous effort; [daḷha + parakkama] |
| daḷha (pp.)           | firm; steady; strenuous                       |
| phusati               | touches; contacts; feels; experiences         |
| yoga (m.)             | yoke; bond; attachment                        |

*** Links                                                          :noexport:

[[http://localhost:4848/suttas/dhp21-32/pli/ms?quote=Appam%25C4%2581do%2520amatapada%25E1%25B9%2581&window_type=Sutta+Study][Dhp 21]]
* 2024-12-27
** Ratana sutta: khīṇaṁ purāṇaṁ...

#+begin_quote
Khīṇaṁ purāṇaṁ navaṁ natthi sambhavaṁ,

Viratta- cittāyatike bhavasmiṁ;

Te khīṇa- bījā avirūḷhi- chandā,

Nibbanti dhīrā yathā- yaṁ padīpo;

Idampi saṅghe ratanaṁ paṇītaṁ,

Etena saccena suvatthi hotu.
#+end_quote

#+ATTR_LATEX: :environment longtable :align L{\colOne} L{\colTwo}
| khīyati                       | is destroyed; is exhausted                                 |
| khīṇa (pp. of khīyati)         | consumed; destroyed                                        |
| khaya (m. from khīyati)       | wearing away; destruction                                  |
| purāṇa (adj.)                  | previous; old; ancient                                     |
| nava (adj.)                   | new; fresh                                                 |
| sambhavati                    | comes to be; happens; occurs                               |
| sambhava (m. from sambhavati) | birth; origin; source (of)                                 |
| rajjati                       | finds pleasure (in); is enamoured (with)                   |
| virajjati                     | becomes detached (from); loses interest (in)               |
| viratta (pp. of virajjati)    | detached (from); without desire (for); lost interest (in)  |
| āyati (f.)                    | future; upcoming                                           |
| āyatika (adj. from āyati)     | upcoming; future                                           |
| bīja (nt.)                    | seed; germ                                                 |
| virūḷhi (f.)                   | growth; increase                                           |
| chanda (m.)                   | (1) interest; desire; wish (2) consent; agreement          |
| nibbāti                       | is extinguished; goes out; lit. blows away                 |
| dhīra (adj.)                  | (1) stable; constant; reliable; firm (2) wise; intelligent |
| padīpa (m.)                   | lamp; light; lighting                                      |

(tesaṁ,) purāṇaṁ kammaṁ khīṇaṁ hoti

navaṁ sambhavaṁ natthi

kammaṁ: nt. nom/acc. sg.

kammaṁ khettaṁ, viññāṇaṁ bījaṁ, taṇhā sneho (AN 3.76)

*** Links                                                          :noexport:

[[http://localhost:4848/suttas/snp2.1/pli/ms?quote=Kh%25C4%25AB%25E1%25B9%2587a%25E1%25B9%2581%2520pur%25C4%2581%25E1%25B9%2587a%25E1%25B9%2581&window_type=Sutta+Study][Khīṇaṁ purāṇaṁ...]]

[[https://www.tldraw.com/r/hXdaGU7vKip5vHbAkQa8D?d=v-278.-199.1553.811.page][tldraw board]]

*** Analysis                                                       :noexport:

Provide a word-by-word grammar analysis of the following Pali text.
Indicate omitted subjects, objects or verbs (e.g. hoti).

: Khīṇaṁ purāṇaṁ navaṁ natthi sambhavaṁ,
: Virattacittāyatike bhavasmiṁ;

The construction follows a parallel structure:
[tesaṃ] khīṇaṁ purāṇaṁ [hoti] - "the old is destroyed [for them]"

Khīṇaṁ:
- Root: √khī (to waste away, be exhausted)
- Past participle of khīyati
- Nominative/accusative singular neuter
- Meaning: exhausted, destroyed

purāṇaṁ:
- Adjective
- Nominative/accusative singular neuter
- Meaning: old, former

navaṁ:
- Adjective
- Nominative/accusative singular neuter
- Meaning: new

natthi:
- na (negative particle) + atthi (from √as, to be)
- 3rd person singular present indicative
- Meaning: is not, does not exist

sambhavaṁ:
- Prefix saṁ + √bhū (to become)
- Nominative/accusative singular neuter
- Action noun/gerund
- Meaning: arising, origination

Viratta-cittāyatike:
- Compound word (tatpurusa):
  * viratta: past participle of virajjati (vi + √raj)
  * citta: mind
  * āyatika: future, what lies ahead
- Locative singular
- Meaning: in future becoming

bhavasmiṁ:
- Root: √bhū (to become)
- Locative singular masculine
- Meaning: in existence

: Te khīṇabījā avirūḷhichandā,
: Nibbanti dhīrā yathāyaṁ padīpo;

Te:
- Demonstrative pronoun, nominative plural masculine
- "They, those"

khīṇabījā:
- Compound adjective (bahuvrīhi), nominative plural masculine
- khīṇa (destroyed) + bīja (seed)
- "Those whose seeds are destroyed"

avirūḷhichandā:
- Compound adjective (bahuvrīhi), nominative plural masculine
- a (negative) + virūḷhi (growth) + chanda (desire)
- "Those whose desire for growth has ceased"

Nibbanti:
- Verb, 3rd person plural present indicative
- Root: √nibbā (to be extinguished)
- "They are extinguished"

dhīrā:
- Adjective/noun, nominative plural masculine
- "The wise ones"

yathā:
- Indeclinable, adverb of comparison
- "Just as, like"

ayaṁ:
- Demonstrative pronoun, nominative singular masculine
- "This"

padīpo:
- Noun, nominative singular masculine
- "Lamp"

